// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cursor/v1/cursor.proto

package cursorv1

import (
	v1 "file-indexer/internal/pb/service/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PageToken is the internal wire format of a ListFiles page token. It is
// serialized and base64url-encoded before being returned to clients, and is
// never part of the public API surface (AIP-158: tokens are opaque).
//
// It records the query the token was issued for (sort and filters, so the
// server can reject requests whose arguments changed mid-pagination) and the
// keyset position of the last row returned (last_id plus the sort value
// matching sort_field).
type PageToken struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SortField v1.SortField           `protobuf:"varint,1,opt,name=sort_field,json=sortField,proto3,enum=service.v1.SortField" json:"sort_field,omitempty"`
	SortOrder v1.SortOrder           `protobuf:"varint,2,opt,name=sort_order,json=sortOrder,proto3,enum=service.v1.SortOrder" json:"sort_order,omitempty"`
	// ID of the last row on the previous page; keyset tie-breaker.
	LastId int64 `protobuf:"varint,3,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	// Sort value of the last row; only the field matching sort_field is set.
	Key       string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Matches COALESCE(size_bytes, 0) in the list queries.
	Size int64 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	// Filters the token was issued for, stored raw (before LIKE escaping).
	Prefix        string `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`
	ContentType   string `protobuf:"bytes,8,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageToken) Reset() {
	*x = PageToken{}
	mi := &file_cursor_v1_cursor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageToken) ProtoMessage() {}

func (x *PageToken) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_v1_cursor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageToken.ProtoReflect.Descriptor instead.
func (*PageToken) Descriptor() ([]byte, []int) {
	return file_cursor_v1_cursor_proto_rawDescGZIP(), []int{0}
}

func (x *PageToken) GetSortField() v1.SortField {
	if x != nil {
		return x.SortField
	}
	return v1.SortField(0)
}

func (x *PageToken) GetSortOrder() v1.SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return v1.SortOrder(0)
}

func (x *PageToken) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *PageToken) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PageToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PageToken) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PageToken) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PageToken) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_cursor_v1_cursor_proto protoreflect.FileDescriptor

const file_cursor_v1_cursor_proto_rawDesc = "" +
	"\n" +
	"\x16cursor/v1/cursor.proto\x12\tcursor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17service/v1/search.proto\"\xac\x02\n" +
	"\tPageToken\x124\n" +
	"\n" +
	"sort_field\x18\x01 \x01(\x0e2\x15.service.v1.SortFieldR\tsortField\x124\n" +
	"\n" +
	"sort_order\x18\x02 \x01(\x0e2\x15.service.v1.SortOrderR\tsortOrder\x12\x17\n" +
	"\alast_id\x18\x03 \x01(\x03R\x06lastId\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x16\n" +
	"\x06prefix\x18\a \x01(\tR\x06prefix\x12!\n" +
	"\fcontent_type\x18\b \x01(\tR\vcontentTypeB-Z+file-indexer/internal/pb/cursor/v1;cursorv1b\x06proto3"

var (
	file_cursor_v1_cursor_proto_rawDescOnce sync.Once
	file_cursor_v1_cursor_proto_rawDescData []byte
)

func file_cursor_v1_cursor_proto_rawDescGZIP() []byte {
	file_cursor_v1_cursor_proto_rawDescOnce.Do(func() {
		file_cursor_v1_cursor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cursor_v1_cursor_proto_rawDesc), len(file_cursor_v1_cursor_proto_rawDesc)))
	})
	return file_cursor_v1_cursor_proto_rawDescData
}

var file_cursor_v1_cursor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cursor_v1_cursor_proto_goTypes = []any{
	(*PageToken)(nil),             // 0: cursor.v1.PageToken
	(v1.SortField)(0),             // 1: service.v1.SortField
	(v1.SortOrder)(0),             // 2: service.v1.SortOrder
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_cursor_v1_cursor_proto_depIdxs = []int32{
	1, // 0: cursor.v1.PageToken.sort_field:type_name -> service.v1.SortField
	2, // 1: cursor.v1.PageToken.sort_order:type_name -> service.v1.SortOrder
	3, // 2: cursor.v1.PageToken.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cursor_v1_cursor_proto_init() }
func file_cursor_v1_cursor_proto_init() {
	if File_cursor_v1_cursor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cursor_v1_cursor_proto_rawDesc), len(file_cursor_v1_cursor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cursor_v1_cursor_proto_goTypes,
		DependencyIndexes: file_cursor_v1_cursor_proto_depIdxs,
		MessageInfos:      file_cursor_v1_cursor_proto_msgTypes,
	}.Build()
	File_cursor_v1_cursor_proto = out.File
	file_cursor_v1_cursor_proto_goTypes = nil
	file_cursor_v1_cursor_proto_depIdxs = nil
}
