// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cursor/v1/cursor.proto

package cursorv1

import (
	v1 "file-indexer/internal/pb/service/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListPhase distinguishes the two halves of a ListDirectory page: browse
// mode always lists subdirectories (alphabetical only) before files (which
// honor sort_field/sort_order), so a page's cursor must record which half it
// stopped in.
type ListPhase int32

const (
	ListPhase_LIST_PHASE_UNSPECIFIED ListPhase = 0
	ListPhase_LIST_PHASE_DIRECTORIES ListPhase = 1
	ListPhase_LIST_PHASE_FILES       ListPhase = 2
)

// Enum value maps for ListPhase.
var (
	ListPhase_name = map[int32]string{
		0: "LIST_PHASE_UNSPECIFIED",
		1: "LIST_PHASE_DIRECTORIES",
		2: "LIST_PHASE_FILES",
	}
	ListPhase_value = map[string]int32{
		"LIST_PHASE_UNSPECIFIED": 0,
		"LIST_PHASE_DIRECTORIES": 1,
		"LIST_PHASE_FILES":       2,
	}
)

func (x ListPhase) Enum() *ListPhase {
	p := new(ListPhase)
	*p = x
	return p
}

func (x ListPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_cursor_v1_cursor_proto_enumTypes[0].Descriptor()
}

func (ListPhase) Type() protoreflect.EnumType {
	return &file_cursor_v1_cursor_proto_enumTypes[0]
}

func (x ListPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListPhase.Descriptor instead.
func (ListPhase) EnumDescriptor() ([]byte, []int) {
	return file_cursor_v1_cursor_proto_rawDescGZIP(), []int{0}
}

// PageToken is the internal wire format of a ListFiles page token. It is
// serialized and base64url-encoded before being returned to clients, and is
// never part of the public API surface (AIP-158: tokens are opaque).
//
// It records the query the token was issued for (sort and filters, so the
// server can reject requests whose arguments changed mid-pagination) and the
// keyset position of the last row returned (last_id plus the sort value
// matching sort_field).
type PageToken struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SortField v1.SortField           `protobuf:"varint,1,opt,name=sort_field,json=sortField,proto3,enum=service.v1.SortField" json:"sort_field,omitempty"`
	SortOrder v1.SortOrder           `protobuf:"varint,2,opt,name=sort_order,json=sortOrder,proto3,enum=service.v1.SortOrder" json:"sort_order,omitempty"`
	// ID of the last row on the previous page; keyset tie-breaker.
	LastId int64 `protobuf:"varint,3,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	// Sort value of the last row; only the field matching sort_field is set.
	Key          string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	LastModified *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	// Matches COALESCE(size_bytes, 0) in the list queries.
	Size int64 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	// Filters the token was issued for, stored raw (before LIKE escaping).
	Prefix      string `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`
	ContentType string `protobuf:"bytes,8,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// ListDirectory's own two-phase cursor. path is the directory being
	// browsed (raw, trailing "/"); phase records whether the previous page
	// ended while still listing subdirectories or had moved on to files, so
	// resuming asks the right query for the right position. last_dir is only
	// meaningful in the DIRECTORIES phase (the last child path returned,
	// directly usable as ListChildDirectories' `after` argument — a plain
	// keyset comparison against the directories table); the FILES phase
	// reuses sort_field/sort_order/last_id/key/last_modified/size above,
	// exactly like ListFiles' cursor.
	Path          string    `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
	Phase         ListPhase `protobuf:"varint,10,opt,name=phase,proto3,enum=cursor.v1.ListPhase" json:"phase,omitempty"`
	LastDir       string    `protobuf:"bytes,11,opt,name=last_dir,json=lastDir,proto3" json:"last_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageToken) Reset() {
	*x = PageToken{}
	mi := &file_cursor_v1_cursor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageToken) ProtoMessage() {}

func (x *PageToken) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_v1_cursor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageToken.ProtoReflect.Descriptor instead.
func (*PageToken) Descriptor() ([]byte, []int) {
	return file_cursor_v1_cursor_proto_rawDescGZIP(), []int{0}
}

func (x *PageToken) GetSortField() v1.SortField {
	if x != nil {
		return x.SortField
	}
	return v1.SortField(0)
}

func (x *PageToken) GetSortOrder() v1.SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return v1.SortOrder(0)
}

func (x *PageToken) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *PageToken) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PageToken) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

func (x *PageToken) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PageToken) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PageToken) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PageToken) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PageToken) GetPhase() ListPhase {
	if x != nil {
		return x.Phase
	}
	return ListPhase_LIST_PHASE_UNSPECIFIED
}

func (x *PageToken) GetLastDir() string {
	if x != nil {
		return x.LastDir
	}
	return ""
}

var File_cursor_v1_cursor_proto protoreflect.FileDescriptor

const file_cursor_v1_cursor_proto_rawDesc = "" +
	"\n" +
	"\x16cursor/v1/cursor.proto\x12\tcursor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17service/v1/search.proto\"\x8d\x03\n" +
	"\tPageToken\x124\n" +
	"\n" +
	"sort_field\x18\x01 \x01(\x0e2\x15.service.v1.SortFieldR\tsortField\x124\n" +
	"\n" +
	"sort_order\x18\x02 \x01(\x0e2\x15.service.v1.SortOrderR\tsortOrder\x12\x17\n" +
	"\alast_id\x18\x03 \x01(\x03R\x06lastId\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12?\n" +
	"\rlast_modified\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x16\n" +
	"\x06prefix\x18\a \x01(\tR\x06prefix\x12!\n" +
	"\fcontent_type\x18\b \x01(\tR\vcontentType\x12\x12\n" +
	"\x04path\x18\t \x01(\tR\x04path\x12*\n" +
	"\x05phase\x18\n" +
	" \x01(\x0e2\x14.cursor.v1.ListPhaseR\x05phase\x12\x19\n" +
	"\blast_dir\x18\v \x01(\tR\alastDir*Y\n" +
	"\tListPhase\x12\x1a\n" +
	"\x16LIST_PHASE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16LIST_PHASE_DIRECTORIES\x10\x01\x12\x14\n" +
	"\x10LIST_PHASE_FILES\x10\x02B-Z+file-indexer/internal/pb/cursor/v1;cursorv1b\x06proto3"

var (
	file_cursor_v1_cursor_proto_rawDescOnce sync.Once
	file_cursor_v1_cursor_proto_rawDescData []byte
)

func file_cursor_v1_cursor_proto_rawDescGZIP() []byte {
	file_cursor_v1_cursor_proto_rawDescOnce.Do(func() {
		file_cursor_v1_cursor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cursor_v1_cursor_proto_rawDesc), len(file_cursor_v1_cursor_proto_rawDesc)))
	})
	return file_cursor_v1_cursor_proto_rawDescData
}

var file_cursor_v1_cursor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cursor_v1_cursor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cursor_v1_cursor_proto_goTypes = []any{
	(ListPhase)(0),                // 0: cursor.v1.ListPhase
	(*PageToken)(nil),             // 1: cursor.v1.PageToken
	(v1.SortField)(0),             // 2: service.v1.SortField
	(v1.SortOrder)(0),             // 3: service.v1.SortOrder
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_cursor_v1_cursor_proto_depIdxs = []int32{
	2, // 0: cursor.v1.PageToken.sort_field:type_name -> service.v1.SortField
	3, // 1: cursor.v1.PageToken.sort_order:type_name -> service.v1.SortOrder
	4, // 2: cursor.v1.PageToken.last_modified:type_name -> google.protobuf.Timestamp
	0, // 3: cursor.v1.PageToken.phase:type_name -> cursor.v1.ListPhase
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cursor_v1_cursor_proto_init() }
func file_cursor_v1_cursor_proto_init() {
	if File_cursor_v1_cursor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cursor_v1_cursor_proto_rawDesc), len(file_cursor_v1_cursor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cursor_v1_cursor_proto_goTypes,
		DependencyIndexes: file_cursor_v1_cursor_proto_depIdxs,
		EnumInfos:         file_cursor_v1_cursor_proto_enumTypes,
		MessageInfos:      file_cursor_v1_cursor_proto_msgTypes,
	}.Build()
	File_cursor_v1_cursor_proto = out.File
	file_cursor_v1_cursor_proto_goTypes = nil
	file_cursor_v1_cursor_proto_depIdxs = nil
}
