all: false
dir: "{{.InterfaceDir}}"
filename: "mocks_test.go"
structname: "Mock{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
packages:
  file-indexer/internal/service/files:
    interfaces:
      ObjectStore:
      FileIndex:
  file-indexer/internal/service/indexer:
    interfaces:
      ObjectStore:
      PreviewObjectStore:
      Queries:
  file-indexer/internal/service/crawler:
    interfaces:
      ObjectStore:
      FileStore:
  file-indexer/internal/service/search:
    interfaces:
      FileIndex:
