// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (source, path, content_type, size_bytes)
VALUES ($1, $2, $3, $4)
RETURNING id, source, path, content_type, size_bytes, created_at, updated_at
`

type CreateFileParams struct {
	Source      string
	Path        string
	ContentType pgtype.Text
	SizeBytes   pgtype.Int8
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.Source,
		arg.Path,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Path,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
