// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package files

import (
	"context"
	"file-indexer/internal/db"

	mock "github.com/stretchr/testify/mock"
)

// NewMockObjectStore creates a new instance of MockObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStore {
	mock := &MockObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectStore is an autogenerated mock type for the ObjectStore type
type MockObjectStore struct {
	mock.Mock
}

type MockObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStore) EXPECT() *MockObjectStore_Expecter {
	return &MockObjectStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockObjectStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) Delete(ctx any, key any) *MockObjectStore_Delete_Call {
	return &MockObjectStore_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockObjectStore_Delete_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_Delete_Call) Return(err error) *MockObjectStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectStore_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockObjectStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) GetURL(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStore_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockObjectStore_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) GetURL(ctx any, key any) *MockObjectStore_GetURL_Call {
	return &MockObjectStore_GetURL_Call{Call: _e.mock.On("GetURL", ctx, key)}
}

func (_c *MockObjectStore_GetURL_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_GetURL_Call) Return(s string, err error) *MockObjectStore_GetURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockObjectStore_GetURL_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockObjectStore_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileIndex creates a new instance of MockFileIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileIndex {
	mock := &MockFileIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileIndex is an autogenerated mock type for the FileIndex type
type MockFileIndex struct {
	mock.Mock
}

type MockFileIndex_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileIndex) EXPECT() *MockFileIndex_Expecter {
	return &MockFileIndex_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) DeleteFile(ctx context.Context, id int64) (db.File, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 db.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (db.File, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) db.File); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.File)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockFileIndex_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockFileIndex_Expecter) DeleteFile(ctx any, id any) *MockFileIndex_DeleteFile_Call {
	return &MockFileIndex_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, id)}
}

func (_c *MockFileIndex_DeleteFile_Call) Run(run func(ctx context.Context, id int64)) *MockFileIndex_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_DeleteFile_Call) Return(file db.File, err error) *MockFileIndex_DeleteFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileIndex_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, id int64) (db.File, error)) *MockFileIndex_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) GetFile(ctx context.Context, id int64) (db.FileInfo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 db.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (db.FileInfo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) db.FileInfo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.FileInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type MockFileIndex_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockFileIndex_Expecter) GetFile(ctx any, id any) *MockFileIndex_GetFile_Call {
	return &MockFileIndex_GetFile_Call{Call: _e.mock.On("GetFile", ctx, id)}
}

func (_c *MockFileIndex_GetFile_Call) Run(run func(ctx context.Context, id int64)) *MockFileIndex_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_GetFile_Call) Return(fileInfo db.FileInfo, err error) *MockFileIndex_GetFile_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockFileIndex_GetFile_Call) RunAndReturn(run func(ctx context.Context, id int64) (db.FileInfo, error)) *MockFileIndex_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilesByIDs provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) GetFilesByIDs(ctx context.Context, ids []int64) ([]db.FileInfo, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesByIDs")
	}

	var r0 []db.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) ([]db.FileInfo, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) []db.FileInfo); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_GetFilesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesByIDs'
type MockFileIndex_GetFilesByIDs_Call struct {
	*mock.Call
}

// GetFilesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockFileIndex_Expecter) GetFilesByIDs(ctx any, ids any) *MockFileIndex_GetFilesByIDs_Call {
	return &MockFileIndex_GetFilesByIDs_Call{Call: _e.mock.On("GetFilesByIDs", ctx, ids)}
}

func (_c *MockFileIndex_GetFilesByIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockFileIndex_GetFilesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_GetFilesByIDs_Call) Return(fileInfos []db.FileInfo, err error) *MockFileIndex_GetFilesByIDs_Call {
	_c.Call.Return(fileInfos, err)
	return _c
}

func (_c *MockFileIndex_GetFilesByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []int64) ([]db.FileInfo, error)) *MockFileIndex_GetFilesByIDs_Call {
	_c.Call.Return(run)
	return _c
}
