// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package files

import (
	"context"
	"file-indexer/internal/db"
	"file-indexer/internal/storage"

	mock "github.com/stretchr/testify/mock"
)

// NewMockObjectStore creates a new instance of MockObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStore {
	mock := &MockObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectStore is an autogenerated mock type for the ObjectStore type
type MockObjectStore struct {
	mock.Mock
}

type MockObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStore) EXPECT() *MockObjectStore_Expecter {
	return &MockObjectStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockObjectStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) Delete(ctx any, key any) *MockObjectStore_Delete_Call {
	return &MockObjectStore_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockObjectStore_Delete_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_Delete_Call) Return(err error) *MockObjectStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectStore_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockObjectStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) DeleteMany(ctx context.Context, keys []string) error {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectStore_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockObjectStore_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockObjectStore_Expecter) DeleteMany(ctx any, keys any) *MockObjectStore_DeleteMany_Call {
	return &MockObjectStore_DeleteMany_Call{Call: _e.mock.On("DeleteMany", ctx, keys)}
}

func (_c *MockObjectStore_DeleteMany_Call) Run(run func(ctx context.Context, keys []string)) *MockObjectStore_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_DeleteMany_Call) Return(err error) *MockObjectStore_DeleteMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectStore_DeleteMany_Call) RunAndReturn(run func(ctx context.Context, keys []string) error) *MockObjectStore_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// GetInlineURL provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) GetInlineURL(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetInlineURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStore_GetInlineURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInlineURL'
type MockObjectStore_GetInlineURL_Call struct {
	*mock.Call
}

// GetInlineURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) GetInlineURL(ctx any, key any) *MockObjectStore_GetInlineURL_Call {
	return &MockObjectStore_GetInlineURL_Call{Call: _e.mock.On("GetInlineURL", ctx, key)}
}

func (_c *MockObjectStore_GetInlineURL_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_GetInlineURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_GetInlineURL_Call) Return(s string, err error) *MockObjectStore_GetInlineURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockObjectStore_GetInlineURL_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockObjectStore_GetInlineURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) GetURL(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStore_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockObjectStore_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) GetURL(ctx any, key any) *MockObjectStore_GetURL_Call {
	return &MockObjectStore_GetURL_Call{Call: _e.mock.On("GetURL", ctx, key)}
}

func (_c *MockObjectStore_GetURL_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_GetURL_Call) Return(s string, err error) *MockObjectStore_GetURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockObjectStore_GetURL_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockObjectStore_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// PutURL provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) PutURL(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for PutURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStore_PutURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutURL'
type MockObjectStore_PutURL_Call struct {
	*mock.Call
}

// PutURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) PutURL(ctx any, key any) *MockObjectStore_PutURL_Call {
	return &MockObjectStore_PutURL_Call{Call: _e.mock.On("PutURL", ctx, key)}
}

func (_c *MockObjectStore_PutURL_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_PutURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_PutURL_Call) Return(s string, err error) *MockObjectStore_PutURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockObjectStore_PutURL_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockObjectStore_PutURL_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) Stat(ctx context.Context, key string) (storage.ObjectInfo, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 storage.ObjectInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (storage.ObjectInfo, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) storage.ObjectInfo); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(storage.ObjectInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStore_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockObjectStore_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) Stat(ctx any, key any) *MockObjectStore_Stat_Call {
	return &MockObjectStore_Stat_Call{Call: _e.mock.On("Stat", ctx, key)}
}

func (_c *MockObjectStore_Stat_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_Stat_Call) Return(objectInfo storage.ObjectInfo, err error) *MockObjectStore_Stat_Call {
	_c.Call.Return(objectInfo, err)
	return _c
}

func (_c *MockObjectStore_Stat_Call) RunAndReturn(run func(ctx context.Context, key string) (storage.ObjectInfo, error)) *MockObjectStore_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileIndex creates a new instance of MockFileIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileIndex {
	mock := &MockFileIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileIndex is an autogenerated mock type for the FileIndex type
type MockFileIndex struct {
	mock.Mock
}

type MockFileIndex_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileIndex) EXPECT() *MockFileIndex_Expecter {
	return &MockFileIndex_Expecter{mock: &_m.Mock}
}

// DeleteFileWithDirectories provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) DeleteFileWithDirectories(ctx context.Context, id int64) (db.File, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFileWithDirectories")
	}

	var r0 db.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (db.File, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) db.File); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.File)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_DeleteFileWithDirectories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFileWithDirectories'
type MockFileIndex_DeleteFileWithDirectories_Call struct {
	*mock.Call
}

// DeleteFileWithDirectories is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockFileIndex_Expecter) DeleteFileWithDirectories(ctx any, id any) *MockFileIndex_DeleteFileWithDirectories_Call {
	return &MockFileIndex_DeleteFileWithDirectories_Call{Call: _e.mock.On("DeleteFileWithDirectories", ctx, id)}
}

func (_c *MockFileIndex_DeleteFileWithDirectories_Call) Run(run func(ctx context.Context, id int64)) *MockFileIndex_DeleteFileWithDirectories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_DeleteFileWithDirectories_Call) Return(file db.File, err error) *MockFileIndex_DeleteFileWithDirectories_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileIndex_DeleteFileWithDirectories_Call) RunAndReturn(run func(ctx context.Context, id int64) (db.File, error)) *MockFileIndex_DeleteFileWithDirectories_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFilesByIDsWithDirectories provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) DeleteFilesByIDsWithDirectories(ctx context.Context, ids []int64, keys []string) (int64, error) {
	ret := _mock.Called(ctx, ids, keys)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFilesByIDsWithDirectories")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64, []string) (int64, error)); ok {
		return returnFunc(ctx, ids, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64, []string) int64); ok {
		r0 = returnFunc(ctx, ids, keys)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64, []string) error); ok {
		r1 = returnFunc(ctx, ids, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_DeleteFilesByIDsWithDirectories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFilesByIDsWithDirectories'
type MockFileIndex_DeleteFilesByIDsWithDirectories_Call struct {
	*mock.Call
}

// DeleteFilesByIDsWithDirectories is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
//   - keys []string
func (_e *MockFileIndex_Expecter) DeleteFilesByIDsWithDirectories(ctx any, ids any, keys any) *MockFileIndex_DeleteFilesByIDsWithDirectories_Call {
	return &MockFileIndex_DeleteFilesByIDsWithDirectories_Call{Call: _e.mock.On("DeleteFilesByIDsWithDirectories", ctx, ids, keys)}
}

func (_c *MockFileIndex_DeleteFilesByIDsWithDirectories_Call) Run(run func(ctx context.Context, ids []int64, keys []string)) *MockFileIndex_DeleteFilesByIDsWithDirectories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileIndex_DeleteFilesByIDsWithDirectories_Call) Return(n int64, err error) *MockFileIndex_DeleteFilesByIDsWithDirectories_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFileIndex_DeleteFilesByIDsWithDirectories_Call) RunAndReturn(run func(ctx context.Context, ids []int64, keys []string) (int64, error)) *MockFileIndex_DeleteFilesByIDsWithDirectories_Call {
	_c.Call.Return(run)
	return _c
}

// GetDirectoryStats provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) GetDirectoryStats(ctx context.Context, keyPattern string) (db.GetDirectoryStatsRow, error) {
	ret := _mock.Called(ctx, keyPattern)

	if len(ret) == 0 {
		panic("no return value specified for GetDirectoryStats")
	}

	var r0 db.GetDirectoryStatsRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (db.GetDirectoryStatsRow, error)); ok {
		return returnFunc(ctx, keyPattern)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) db.GetDirectoryStatsRow); ok {
		r0 = returnFunc(ctx, keyPattern)
	} else {
		r0 = ret.Get(0).(db.GetDirectoryStatsRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, keyPattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_GetDirectoryStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDirectoryStats'
type MockFileIndex_GetDirectoryStats_Call struct {
	*mock.Call
}

// GetDirectoryStats is a helper method to define mock.On call
//   - ctx context.Context
//   - keyPattern string
func (_e *MockFileIndex_Expecter) GetDirectoryStats(ctx any, keyPattern any) *MockFileIndex_GetDirectoryStats_Call {
	return &MockFileIndex_GetDirectoryStats_Call{Call: _e.mock.On("GetDirectoryStats", ctx, keyPattern)}
}

func (_c *MockFileIndex_GetDirectoryStats_Call) Run(run func(ctx context.Context, keyPattern string)) *MockFileIndex_GetDirectoryStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_GetDirectoryStats_Call) Return(getDirectoryStatsRow db.GetDirectoryStatsRow, err error) *MockFileIndex_GetDirectoryStats_Call {
	_c.Call.Return(getDirectoryStatsRow, err)
	return _c
}

func (_c *MockFileIndex_GetDirectoryStats_Call) RunAndReturn(run func(ctx context.Context, keyPattern string) (db.GetDirectoryStatsRow, error)) *MockFileIndex_GetDirectoryStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) GetFile(ctx context.Context, id int64) (db.FileInfo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 db.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (db.FileInfo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) db.FileInfo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.FileInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type MockFileIndex_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockFileIndex_Expecter) GetFile(ctx any, id any) *MockFileIndex_GetFile_Call {
	return &MockFileIndex_GetFile_Call{Call: _e.mock.On("GetFile", ctx, id)}
}

func (_c *MockFileIndex_GetFile_Call) Run(run func(ctx context.Context, id int64)) *MockFileIndex_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_GetFile_Call) Return(fileInfo db.FileInfo, err error) *MockFileIndex_GetFile_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockFileIndex_GetFile_Call) RunAndReturn(run func(ctx context.Context, id int64) (db.FileInfo, error)) *MockFileIndex_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByKey provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) GetFileByKey(ctx context.Context, key string) (db.FileInfo, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByKey")
	}

	var r0 db.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (db.FileInfo, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) db.FileInfo); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(db.FileInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_GetFileByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByKey'
type MockFileIndex_GetFileByKey_Call struct {
	*mock.Call
}

// GetFileByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockFileIndex_Expecter) GetFileByKey(ctx any, key any) *MockFileIndex_GetFileByKey_Call {
	return &MockFileIndex_GetFileByKey_Call{Call: _e.mock.On("GetFileByKey", ctx, key)}
}

func (_c *MockFileIndex_GetFileByKey_Call) Run(run func(ctx context.Context, key string)) *MockFileIndex_GetFileByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_GetFileByKey_Call) Return(fileInfo db.FileInfo, err error) *MockFileIndex_GetFileByKey_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockFileIndex_GetFileByKey_Call) RunAndReturn(run func(ctx context.Context, key string) (db.FileInfo, error)) *MockFileIndex_GetFileByKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilesByIDs provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) GetFilesByIDs(ctx context.Context, ids []int64) ([]db.FileInfo, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesByIDs")
	}

	var r0 []db.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) ([]db.FileInfo, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) []db.FileInfo); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_GetFilesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesByIDs'
type MockFileIndex_GetFilesByIDs_Call struct {
	*mock.Call
}

// GetFilesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockFileIndex_Expecter) GetFilesByIDs(ctx any, ids any) *MockFileIndex_GetFilesByIDs_Call {
	return &MockFileIndex_GetFilesByIDs_Call{Call: _e.mock.On("GetFilesByIDs", ctx, ids)}
}

func (_c *MockFileIndex_GetFilesByIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockFileIndex_GetFilesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_GetFilesByIDs_Call) Return(fileInfos []db.FileInfo, err error) *MockFileIndex_GetFilesByIDs_Call {
	_c.Call.Return(fileInfos, err)
	return _c
}

func (_c *MockFileIndex_GetFilesByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []int64) ([]db.FileInfo, error)) *MockFileIndex_GetFilesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetIndexExifResult provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) GetIndexExifResult(ctx context.Context, fileID int64) (db.IndexExifResult, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetIndexExifResult")
	}

	var r0 db.IndexExifResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (db.IndexExifResult, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) db.IndexExifResult); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Get(0).(db.IndexExifResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_GetIndexExifResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIndexExifResult'
type MockFileIndex_GetIndexExifResult_Call struct {
	*mock.Call
}

// GetIndexExifResult is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID int64
func (_e *MockFileIndex_Expecter) GetIndexExifResult(ctx any, fileID any) *MockFileIndex_GetIndexExifResult_Call {
	return &MockFileIndex_GetIndexExifResult_Call{Call: _e.mock.On("GetIndexExifResult", ctx, fileID)}
}

func (_c *MockFileIndex_GetIndexExifResult_Call) Run(run func(ctx context.Context, fileID int64)) *MockFileIndex_GetIndexExifResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_GetIndexExifResult_Call) Return(indexExifResult db.IndexExifResult, err error) *MockFileIndex_GetIndexExifResult_Call {
	_c.Call.Return(indexExifResult, err)
	return _c
}

func (_c *MockFileIndex_GetIndexExifResult_Call) RunAndReturn(run func(ctx context.Context, fileID int64) (db.IndexExifResult, error)) *MockFileIndex_GetIndexExifResult_Call {
	_c.Call.Return(run)
	return _c
}

// GetIndexQueueStatuses provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) GetIndexQueueStatuses(ctx context.Context, arg db.GetIndexQueueStatusesParams) ([]db.GetIndexQueueStatusesRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetIndexQueueStatuses")
	}

	var r0 []db.GetIndexQueueStatusesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetIndexQueueStatusesParams) ([]db.GetIndexQueueStatusesRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetIndexQueueStatusesParams) []db.GetIndexQueueStatusesRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetIndexQueueStatusesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.GetIndexQueueStatusesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_GetIndexQueueStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIndexQueueStatuses'
type MockFileIndex_GetIndexQueueStatuses_Call struct {
	*mock.Call
}

// GetIndexQueueStatuses is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetIndexQueueStatusesParams
func (_e *MockFileIndex_Expecter) GetIndexQueueStatuses(ctx any, arg any) *MockFileIndex_GetIndexQueueStatuses_Call {
	return &MockFileIndex_GetIndexQueueStatuses_Call{Call: _e.mock.On("GetIndexQueueStatuses", ctx, arg)}
}

func (_c *MockFileIndex_GetIndexQueueStatuses_Call) Run(run func(ctx context.Context, arg db.GetIndexQueueStatusesParams)) *MockFileIndex_GetIndexQueueStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.GetIndexQueueStatusesParams
		if args[1] != nil {
			arg1 = args[1].(db.GetIndexQueueStatusesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_GetIndexQueueStatuses_Call) Return(getIndexQueueStatusesRows []db.GetIndexQueueStatusesRow, err error) *MockFileIndex_GetIndexQueueStatuses_Call {
	_c.Call.Return(getIndexQueueStatusesRows, err)
	return _c
}

func (_c *MockFileIndex_GetIndexQueueStatuses_Call) RunAndReturn(run func(ctx context.Context, arg db.GetIndexQueueStatusesParams) ([]db.GetIndexQueueStatusesRow, error)) *MockFileIndex_GetIndexQueueStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesForDelete provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListFilesForDelete(ctx context.Context, arg db.ListFilesForDeleteParams) ([]db.ListFilesForDeleteRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesForDelete")
	}

	var r0 []db.ListFilesForDeleteRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesForDeleteParams) ([]db.ListFilesForDeleteRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesForDeleteParams) []db.ListFilesForDeleteRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ListFilesForDeleteRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListFilesForDeleteParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListFilesForDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesForDelete'
type MockFileIndex_ListFilesForDelete_Call struct {
	*mock.Call
}

// ListFilesForDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListFilesForDeleteParams
func (_e *MockFileIndex_Expecter) ListFilesForDelete(ctx any, arg any) *MockFileIndex_ListFilesForDelete_Call {
	return &MockFileIndex_ListFilesForDelete_Call{Call: _e.mock.On("ListFilesForDelete", ctx, arg)}
}

func (_c *MockFileIndex_ListFilesForDelete_Call) Run(run func(ctx context.Context, arg db.ListFilesForDeleteParams)) *MockFileIndex_ListFilesForDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListFilesForDeleteParams
		if args[1] != nil {
			arg1 = args[1].(db.ListFilesForDeleteParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListFilesForDelete_Call) Return(listFilesForDeleteRows []db.ListFilesForDeleteRow, err error) *MockFileIndex_ListFilesForDelete_Call {
	_c.Call.Return(listFilesForDeleteRows, err)
	return _c
}

func (_c *MockFileIndex_ListFilesForDelete_Call) RunAndReturn(run func(ctx context.Context, arg db.ListFilesForDeleteParams) ([]db.ListFilesForDeleteRow, error)) *MockFileIndex_ListFilesForDelete_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertFilesWithDirectories provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) UpsertFilesWithDirectories(ctx context.Context, arg db.UpsertFilesParams) (int64, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertFilesWithDirectories")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpsertFilesParams) (int64, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpsertFilesParams) int64); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.UpsertFilesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_UpsertFilesWithDirectories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertFilesWithDirectories'
type MockFileIndex_UpsertFilesWithDirectories_Call struct {
	*mock.Call
}

// UpsertFilesWithDirectories is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpsertFilesParams
func (_e *MockFileIndex_Expecter) UpsertFilesWithDirectories(ctx any, arg any) *MockFileIndex_UpsertFilesWithDirectories_Call {
	return &MockFileIndex_UpsertFilesWithDirectories_Call{Call: _e.mock.On("UpsertFilesWithDirectories", ctx, arg)}
}

func (_c *MockFileIndex_UpsertFilesWithDirectories_Call) Run(run func(ctx context.Context, arg db.UpsertFilesParams)) *MockFileIndex_UpsertFilesWithDirectories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.UpsertFilesParams
		if args[1] != nil {
			arg1 = args[1].(db.UpsertFilesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_UpsertFilesWithDirectories_Call) Return(n int64, err error) *MockFileIndex_UpsertFilesWithDirectories_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFileIndex_UpsertFilesWithDirectories_Call) RunAndReturn(run func(ctx context.Context, arg db.UpsertFilesParams) (int64, error)) *MockFileIndex_UpsertFilesWithDirectories_Call {
	_c.Call.Return(run)
	return _c
}
