// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package search

import (
	"context"
	"file-indexer/internal/db"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileIndex creates a new instance of MockFileIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileIndex {
	mock := &MockFileIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileIndex is an autogenerated mock type for the FileIndex type
type MockFileIndex struct {
	mock.Mock
}

type MockFileIndex_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileIndex) EXPECT() *MockFileIndex_Expecter {
	return &MockFileIndex_Expecter{mock: &_m.Mock}
}

// ListFilesByCreatedAtAsc provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListFilesByCreatedAtAsc(ctx context.Context, arg db.ListFilesByCreatedAtAscParams) ([]db.File, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesByCreatedAtAsc")
	}

	var r0 []db.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByCreatedAtAscParams) ([]db.File, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByCreatedAtAscParams) []db.File); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListFilesByCreatedAtAscParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListFilesByCreatedAtAsc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesByCreatedAtAsc'
type MockFileIndex_ListFilesByCreatedAtAsc_Call struct {
	*mock.Call
}

// ListFilesByCreatedAtAsc is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListFilesByCreatedAtAscParams
func (_e *MockFileIndex_Expecter) ListFilesByCreatedAtAsc(ctx any, arg any) *MockFileIndex_ListFilesByCreatedAtAsc_Call {
	return &MockFileIndex_ListFilesByCreatedAtAsc_Call{Call: _e.mock.On("ListFilesByCreatedAtAsc", ctx, arg)}
}

func (_c *MockFileIndex_ListFilesByCreatedAtAsc_Call) Run(run func(ctx context.Context, arg db.ListFilesByCreatedAtAscParams)) *MockFileIndex_ListFilesByCreatedAtAsc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListFilesByCreatedAtAscParams
		if args[1] != nil {
			arg1 = args[1].(db.ListFilesByCreatedAtAscParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListFilesByCreatedAtAsc_Call) Return(files []db.File, err error) *MockFileIndex_ListFilesByCreatedAtAsc_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileIndex_ListFilesByCreatedAtAsc_Call) RunAndReturn(run func(ctx context.Context, arg db.ListFilesByCreatedAtAscParams) ([]db.File, error)) *MockFileIndex_ListFilesByCreatedAtAsc_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesByCreatedAtDesc provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListFilesByCreatedAtDesc(ctx context.Context, arg db.ListFilesByCreatedAtDescParams) ([]db.File, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesByCreatedAtDesc")
	}

	var r0 []db.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByCreatedAtDescParams) ([]db.File, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByCreatedAtDescParams) []db.File); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListFilesByCreatedAtDescParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListFilesByCreatedAtDesc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesByCreatedAtDesc'
type MockFileIndex_ListFilesByCreatedAtDesc_Call struct {
	*mock.Call
}

// ListFilesByCreatedAtDesc is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListFilesByCreatedAtDescParams
func (_e *MockFileIndex_Expecter) ListFilesByCreatedAtDesc(ctx any, arg any) *MockFileIndex_ListFilesByCreatedAtDesc_Call {
	return &MockFileIndex_ListFilesByCreatedAtDesc_Call{Call: _e.mock.On("ListFilesByCreatedAtDesc", ctx, arg)}
}

func (_c *MockFileIndex_ListFilesByCreatedAtDesc_Call) Run(run func(ctx context.Context, arg db.ListFilesByCreatedAtDescParams)) *MockFileIndex_ListFilesByCreatedAtDesc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListFilesByCreatedAtDescParams
		if args[1] != nil {
			arg1 = args[1].(db.ListFilesByCreatedAtDescParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListFilesByCreatedAtDesc_Call) Return(files []db.File, err error) *MockFileIndex_ListFilesByCreatedAtDesc_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileIndex_ListFilesByCreatedAtDesc_Call) RunAndReturn(run func(ctx context.Context, arg db.ListFilesByCreatedAtDescParams) ([]db.File, error)) *MockFileIndex_ListFilesByCreatedAtDesc_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesByKeyAsc provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListFilesByKeyAsc(ctx context.Context, arg db.ListFilesByKeyAscParams) ([]db.File, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesByKeyAsc")
	}

	var r0 []db.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByKeyAscParams) ([]db.File, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByKeyAscParams) []db.File); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListFilesByKeyAscParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListFilesByKeyAsc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesByKeyAsc'
type MockFileIndex_ListFilesByKeyAsc_Call struct {
	*mock.Call
}

// ListFilesByKeyAsc is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListFilesByKeyAscParams
func (_e *MockFileIndex_Expecter) ListFilesByKeyAsc(ctx any, arg any) *MockFileIndex_ListFilesByKeyAsc_Call {
	return &MockFileIndex_ListFilesByKeyAsc_Call{Call: _e.mock.On("ListFilesByKeyAsc", ctx, arg)}
}

func (_c *MockFileIndex_ListFilesByKeyAsc_Call) Run(run func(ctx context.Context, arg db.ListFilesByKeyAscParams)) *MockFileIndex_ListFilesByKeyAsc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListFilesByKeyAscParams
		if args[1] != nil {
			arg1 = args[1].(db.ListFilesByKeyAscParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListFilesByKeyAsc_Call) Return(files []db.File, err error) *MockFileIndex_ListFilesByKeyAsc_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileIndex_ListFilesByKeyAsc_Call) RunAndReturn(run func(ctx context.Context, arg db.ListFilesByKeyAscParams) ([]db.File, error)) *MockFileIndex_ListFilesByKeyAsc_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesByKeyDesc provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListFilesByKeyDesc(ctx context.Context, arg db.ListFilesByKeyDescParams) ([]db.File, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesByKeyDesc")
	}

	var r0 []db.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByKeyDescParams) ([]db.File, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByKeyDescParams) []db.File); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListFilesByKeyDescParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListFilesByKeyDesc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesByKeyDesc'
type MockFileIndex_ListFilesByKeyDesc_Call struct {
	*mock.Call
}

// ListFilesByKeyDesc is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListFilesByKeyDescParams
func (_e *MockFileIndex_Expecter) ListFilesByKeyDesc(ctx any, arg any) *MockFileIndex_ListFilesByKeyDesc_Call {
	return &MockFileIndex_ListFilesByKeyDesc_Call{Call: _e.mock.On("ListFilesByKeyDesc", ctx, arg)}
}

func (_c *MockFileIndex_ListFilesByKeyDesc_Call) Run(run func(ctx context.Context, arg db.ListFilesByKeyDescParams)) *MockFileIndex_ListFilesByKeyDesc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListFilesByKeyDescParams
		if args[1] != nil {
			arg1 = args[1].(db.ListFilesByKeyDescParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListFilesByKeyDesc_Call) Return(files []db.File, err error) *MockFileIndex_ListFilesByKeyDesc_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileIndex_ListFilesByKeyDesc_Call) RunAndReturn(run func(ctx context.Context, arg db.ListFilesByKeyDescParams) ([]db.File, error)) *MockFileIndex_ListFilesByKeyDesc_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesBySizeAsc provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListFilesBySizeAsc(ctx context.Context, arg db.ListFilesBySizeAscParams) ([]db.File, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesBySizeAsc")
	}

	var r0 []db.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesBySizeAscParams) ([]db.File, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesBySizeAscParams) []db.File); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListFilesBySizeAscParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListFilesBySizeAsc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesBySizeAsc'
type MockFileIndex_ListFilesBySizeAsc_Call struct {
	*mock.Call
}

// ListFilesBySizeAsc is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListFilesBySizeAscParams
func (_e *MockFileIndex_Expecter) ListFilesBySizeAsc(ctx any, arg any) *MockFileIndex_ListFilesBySizeAsc_Call {
	return &MockFileIndex_ListFilesBySizeAsc_Call{Call: _e.mock.On("ListFilesBySizeAsc", ctx, arg)}
}

func (_c *MockFileIndex_ListFilesBySizeAsc_Call) Run(run func(ctx context.Context, arg db.ListFilesBySizeAscParams)) *MockFileIndex_ListFilesBySizeAsc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListFilesBySizeAscParams
		if args[1] != nil {
			arg1 = args[1].(db.ListFilesBySizeAscParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListFilesBySizeAsc_Call) Return(files []db.File, err error) *MockFileIndex_ListFilesBySizeAsc_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileIndex_ListFilesBySizeAsc_Call) RunAndReturn(run func(ctx context.Context, arg db.ListFilesBySizeAscParams) ([]db.File, error)) *MockFileIndex_ListFilesBySizeAsc_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesBySizeDesc provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListFilesBySizeDesc(ctx context.Context, arg db.ListFilesBySizeDescParams) ([]db.File, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesBySizeDesc")
	}

	var r0 []db.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesBySizeDescParams) ([]db.File, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesBySizeDescParams) []db.File); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListFilesBySizeDescParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListFilesBySizeDesc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesBySizeDesc'
type MockFileIndex_ListFilesBySizeDesc_Call struct {
	*mock.Call
}

// ListFilesBySizeDesc is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListFilesBySizeDescParams
func (_e *MockFileIndex_Expecter) ListFilesBySizeDesc(ctx any, arg any) *MockFileIndex_ListFilesBySizeDesc_Call {
	return &MockFileIndex_ListFilesBySizeDesc_Call{Call: _e.mock.On("ListFilesBySizeDesc", ctx, arg)}
}

func (_c *MockFileIndex_ListFilesBySizeDesc_Call) Run(run func(ctx context.Context, arg db.ListFilesBySizeDescParams)) *MockFileIndex_ListFilesBySizeDesc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListFilesBySizeDescParams
		if args[1] != nil {
			arg1 = args[1].(db.ListFilesBySizeDescParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListFilesBySizeDesc_Call) Return(files []db.File, err error) *MockFileIndex_ListFilesBySizeDesc_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileIndex_ListFilesBySizeDesc_Call) RunAndReturn(run func(ctx context.Context, arg db.ListFilesBySizeDescParams) ([]db.File, error)) *MockFileIndex_ListFilesBySizeDesc_Call {
	_c.Call.Return(run)
	return _c
}
