// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package search

import (
	"context"
	"file-indexer/internal/db"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileIndex creates a new instance of MockFileIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileIndex {
	mock := &MockFileIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileIndex is an autogenerated mock type for the FileIndex type
type MockFileIndex struct {
	mock.Mock
}

type MockFileIndex_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileIndex) EXPECT() *MockFileIndex_Expecter {
	return &MockFileIndex_Expecter{mock: &_m.Mock}
}

// GetIndexQueueStatuses provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) GetIndexQueueStatuses(ctx context.Context, arg db.GetIndexQueueStatusesParams) ([]db.GetIndexQueueStatusesRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetIndexQueueStatuses")
	}

	var r0 []db.GetIndexQueueStatusesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetIndexQueueStatusesParams) ([]db.GetIndexQueueStatusesRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetIndexQueueStatusesParams) []db.GetIndexQueueStatusesRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetIndexQueueStatusesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.GetIndexQueueStatusesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_GetIndexQueueStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIndexQueueStatuses'
type MockFileIndex_GetIndexQueueStatuses_Call struct {
	*mock.Call
}

// GetIndexQueueStatuses is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetIndexQueueStatusesParams
func (_e *MockFileIndex_Expecter) GetIndexQueueStatuses(ctx any, arg any) *MockFileIndex_GetIndexQueueStatuses_Call {
	return &MockFileIndex_GetIndexQueueStatuses_Call{Call: _e.mock.On("GetIndexQueueStatuses", ctx, arg)}
}

func (_c *MockFileIndex_GetIndexQueueStatuses_Call) Run(run func(ctx context.Context, arg db.GetIndexQueueStatusesParams)) *MockFileIndex_GetIndexQueueStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.GetIndexQueueStatusesParams
		if args[1] != nil {
			arg1 = args[1].(db.GetIndexQueueStatusesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_GetIndexQueueStatuses_Call) Return(getIndexQueueStatusesRows []db.GetIndexQueueStatusesRow, err error) *MockFileIndex_GetIndexQueueStatuses_Call {
	_c.Call.Return(getIndexQueueStatusesRows, err)
	return _c
}

func (_c *MockFileIndex_GetIndexQueueStatuses_Call) RunAndReturn(run func(ctx context.Context, arg db.GetIndexQueueStatusesParams) ([]db.GetIndexQueueStatusesRow, error)) *MockFileIndex_GetIndexQueueStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// ListChildDirectories provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListChildDirectories(ctx context.Context, arg db.ListChildDirectoriesParams) ([]string, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListChildDirectories")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListChildDirectoriesParams) ([]string, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListChildDirectoriesParams) []string); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListChildDirectoriesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListChildDirectories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListChildDirectories'
type MockFileIndex_ListChildDirectories_Call struct {
	*mock.Call
}

// ListChildDirectories is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListChildDirectoriesParams
func (_e *MockFileIndex_Expecter) ListChildDirectories(ctx any, arg any) *MockFileIndex_ListChildDirectories_Call {
	return &MockFileIndex_ListChildDirectories_Call{Call: _e.mock.On("ListChildDirectories", ctx, arg)}
}

func (_c *MockFileIndex_ListChildDirectories_Call) Run(run func(ctx context.Context, arg db.ListChildDirectoriesParams)) *MockFileIndex_ListChildDirectories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListChildDirectoriesParams
		if args[1] != nil {
			arg1 = args[1].(db.ListChildDirectoriesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListChildDirectories_Call) Return(strings []string, err error) *MockFileIndex_ListChildDirectories_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockFileIndex_ListChildDirectories_Call) RunAndReturn(run func(ctx context.Context, arg db.ListChildDirectoriesParams) ([]string, error)) *MockFileIndex_ListChildDirectories_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesByKeyAsc provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListFilesByKeyAsc(ctx context.Context, arg db.ListFilesByKeyAscParams) ([]db.FileInfo, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesByKeyAsc")
	}

	var r0 []db.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByKeyAscParams) ([]db.FileInfo, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByKeyAscParams) []db.FileInfo); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListFilesByKeyAscParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListFilesByKeyAsc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesByKeyAsc'
type MockFileIndex_ListFilesByKeyAsc_Call struct {
	*mock.Call
}

// ListFilesByKeyAsc is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListFilesByKeyAscParams
func (_e *MockFileIndex_Expecter) ListFilesByKeyAsc(ctx any, arg any) *MockFileIndex_ListFilesByKeyAsc_Call {
	return &MockFileIndex_ListFilesByKeyAsc_Call{Call: _e.mock.On("ListFilesByKeyAsc", ctx, arg)}
}

func (_c *MockFileIndex_ListFilesByKeyAsc_Call) Run(run func(ctx context.Context, arg db.ListFilesByKeyAscParams)) *MockFileIndex_ListFilesByKeyAsc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListFilesByKeyAscParams
		if args[1] != nil {
			arg1 = args[1].(db.ListFilesByKeyAscParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListFilesByKeyAsc_Call) Return(fileInfos []db.FileInfo, err error) *MockFileIndex_ListFilesByKeyAsc_Call {
	_c.Call.Return(fileInfos, err)
	return _c
}

func (_c *MockFileIndex_ListFilesByKeyAsc_Call) RunAndReturn(run func(ctx context.Context, arg db.ListFilesByKeyAscParams) ([]db.FileInfo, error)) *MockFileIndex_ListFilesByKeyAsc_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesByKeyDesc provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListFilesByKeyDesc(ctx context.Context, arg db.ListFilesByKeyDescParams) ([]db.FileInfo, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesByKeyDesc")
	}

	var r0 []db.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByKeyDescParams) ([]db.FileInfo, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByKeyDescParams) []db.FileInfo); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListFilesByKeyDescParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListFilesByKeyDesc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesByKeyDesc'
type MockFileIndex_ListFilesByKeyDesc_Call struct {
	*mock.Call
}

// ListFilesByKeyDesc is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListFilesByKeyDescParams
func (_e *MockFileIndex_Expecter) ListFilesByKeyDesc(ctx any, arg any) *MockFileIndex_ListFilesByKeyDesc_Call {
	return &MockFileIndex_ListFilesByKeyDesc_Call{Call: _e.mock.On("ListFilesByKeyDesc", ctx, arg)}
}

func (_c *MockFileIndex_ListFilesByKeyDesc_Call) Run(run func(ctx context.Context, arg db.ListFilesByKeyDescParams)) *MockFileIndex_ListFilesByKeyDesc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListFilesByKeyDescParams
		if args[1] != nil {
			arg1 = args[1].(db.ListFilesByKeyDescParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListFilesByKeyDesc_Call) Return(fileInfos []db.FileInfo, err error) *MockFileIndex_ListFilesByKeyDesc_Call {
	_c.Call.Return(fileInfos, err)
	return _c
}

func (_c *MockFileIndex_ListFilesByKeyDesc_Call) RunAndReturn(run func(ctx context.Context, arg db.ListFilesByKeyDescParams) ([]db.FileInfo, error)) *MockFileIndex_ListFilesByKeyDesc_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesByLastModifiedAsc provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListFilesByLastModifiedAsc(ctx context.Context, arg db.ListFilesByLastModifiedAscParams) ([]db.FileInfo, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesByLastModifiedAsc")
	}

	var r0 []db.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByLastModifiedAscParams) ([]db.FileInfo, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByLastModifiedAscParams) []db.FileInfo); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListFilesByLastModifiedAscParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListFilesByLastModifiedAsc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesByLastModifiedAsc'
type MockFileIndex_ListFilesByLastModifiedAsc_Call struct {
	*mock.Call
}

// ListFilesByLastModifiedAsc is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListFilesByLastModifiedAscParams
func (_e *MockFileIndex_Expecter) ListFilesByLastModifiedAsc(ctx any, arg any) *MockFileIndex_ListFilesByLastModifiedAsc_Call {
	return &MockFileIndex_ListFilesByLastModifiedAsc_Call{Call: _e.mock.On("ListFilesByLastModifiedAsc", ctx, arg)}
}

func (_c *MockFileIndex_ListFilesByLastModifiedAsc_Call) Run(run func(ctx context.Context, arg db.ListFilesByLastModifiedAscParams)) *MockFileIndex_ListFilesByLastModifiedAsc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListFilesByLastModifiedAscParams
		if args[1] != nil {
			arg1 = args[1].(db.ListFilesByLastModifiedAscParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListFilesByLastModifiedAsc_Call) Return(fileInfos []db.FileInfo, err error) *MockFileIndex_ListFilesByLastModifiedAsc_Call {
	_c.Call.Return(fileInfos, err)
	return _c
}

func (_c *MockFileIndex_ListFilesByLastModifiedAsc_Call) RunAndReturn(run func(ctx context.Context, arg db.ListFilesByLastModifiedAscParams) ([]db.FileInfo, error)) *MockFileIndex_ListFilesByLastModifiedAsc_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesByLastModifiedDesc provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListFilesByLastModifiedDesc(ctx context.Context, arg db.ListFilesByLastModifiedDescParams) ([]db.FileInfo, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesByLastModifiedDesc")
	}

	var r0 []db.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByLastModifiedDescParams) ([]db.FileInfo, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesByLastModifiedDescParams) []db.FileInfo); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListFilesByLastModifiedDescParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListFilesByLastModifiedDesc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesByLastModifiedDesc'
type MockFileIndex_ListFilesByLastModifiedDesc_Call struct {
	*mock.Call
}

// ListFilesByLastModifiedDesc is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListFilesByLastModifiedDescParams
func (_e *MockFileIndex_Expecter) ListFilesByLastModifiedDesc(ctx any, arg any) *MockFileIndex_ListFilesByLastModifiedDesc_Call {
	return &MockFileIndex_ListFilesByLastModifiedDesc_Call{Call: _e.mock.On("ListFilesByLastModifiedDesc", ctx, arg)}
}

func (_c *MockFileIndex_ListFilesByLastModifiedDesc_Call) Run(run func(ctx context.Context, arg db.ListFilesByLastModifiedDescParams)) *MockFileIndex_ListFilesByLastModifiedDesc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListFilesByLastModifiedDescParams
		if args[1] != nil {
			arg1 = args[1].(db.ListFilesByLastModifiedDescParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListFilesByLastModifiedDesc_Call) Return(fileInfos []db.FileInfo, err error) *MockFileIndex_ListFilesByLastModifiedDesc_Call {
	_c.Call.Return(fileInfos, err)
	return _c
}

func (_c *MockFileIndex_ListFilesByLastModifiedDesc_Call) RunAndReturn(run func(ctx context.Context, arg db.ListFilesByLastModifiedDescParams) ([]db.FileInfo, error)) *MockFileIndex_ListFilesByLastModifiedDesc_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesBySizeAsc provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListFilesBySizeAsc(ctx context.Context, arg db.ListFilesBySizeAscParams) ([]db.FileInfo, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesBySizeAsc")
	}

	var r0 []db.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesBySizeAscParams) ([]db.FileInfo, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesBySizeAscParams) []db.FileInfo); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListFilesBySizeAscParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListFilesBySizeAsc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesBySizeAsc'
type MockFileIndex_ListFilesBySizeAsc_Call struct {
	*mock.Call
}

// ListFilesBySizeAsc is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListFilesBySizeAscParams
func (_e *MockFileIndex_Expecter) ListFilesBySizeAsc(ctx any, arg any) *MockFileIndex_ListFilesBySizeAsc_Call {
	return &MockFileIndex_ListFilesBySizeAsc_Call{Call: _e.mock.On("ListFilesBySizeAsc", ctx, arg)}
}

func (_c *MockFileIndex_ListFilesBySizeAsc_Call) Run(run func(ctx context.Context, arg db.ListFilesBySizeAscParams)) *MockFileIndex_ListFilesBySizeAsc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListFilesBySizeAscParams
		if args[1] != nil {
			arg1 = args[1].(db.ListFilesBySizeAscParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListFilesBySizeAsc_Call) Return(fileInfos []db.FileInfo, err error) *MockFileIndex_ListFilesBySizeAsc_Call {
	_c.Call.Return(fileInfos, err)
	return _c
}

func (_c *MockFileIndex_ListFilesBySizeAsc_Call) RunAndReturn(run func(ctx context.Context, arg db.ListFilesBySizeAscParams) ([]db.FileInfo, error)) *MockFileIndex_ListFilesBySizeAsc_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesBySizeDesc provides a mock function for the type MockFileIndex
func (_mock *MockFileIndex) ListFilesBySizeDesc(ctx context.Context, arg db.ListFilesBySizeDescParams) ([]db.FileInfo, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesBySizeDesc")
	}

	var r0 []db.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesBySizeDescParams) ([]db.FileInfo, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListFilesBySizeDescParams) []db.FileInfo); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListFilesBySizeDescParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIndex_ListFilesBySizeDesc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesBySizeDesc'
type MockFileIndex_ListFilesBySizeDesc_Call struct {
	*mock.Call
}

// ListFilesBySizeDesc is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListFilesBySizeDescParams
func (_e *MockFileIndex_Expecter) ListFilesBySizeDesc(ctx any, arg any) *MockFileIndex_ListFilesBySizeDesc_Call {
	return &MockFileIndex_ListFilesBySizeDesc_Call{Call: _e.mock.On("ListFilesBySizeDesc", ctx, arg)}
}

func (_c *MockFileIndex_ListFilesBySizeDesc_Call) Run(run func(ctx context.Context, arg db.ListFilesBySizeDescParams)) *MockFileIndex_ListFilesBySizeDesc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListFilesBySizeDescParams
		if args[1] != nil {
			arg1 = args[1].(db.ListFilesBySizeDescParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIndex_ListFilesBySizeDesc_Call) Return(fileInfos []db.FileInfo, err error) *MockFileIndex_ListFilesBySizeDesc_Call {
	_c.Call.Return(fileInfos, err)
	return _c
}

func (_c *MockFileIndex_ListFilesBySizeDesc_Call) RunAndReturn(run func(ctx context.Context, arg db.ListFilesBySizeDescParams) ([]db.FileInfo, error)) *MockFileIndex_ListFilesBySizeDesc_Call {
	_c.Call.Return(run)
	return _c
}
