// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: service/v1/files.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PreviewStatus describes a file's position in the preview index pipeline.
type PreviewStatus int32

const (
	// The RPC did not compute a status.
	PreviewStatus_PREVIEW_STATUS_UNSPECIFIED PreviewStatus = 0
	// No preview exists and none is coming: the file is not an image, or the
	// preview indexer processed it and produced nothing (e.g. unsupported or
	// oversized source).
	PreviewStatus_PREVIEW_STATUS_NONE PreviewStatus = 1
	// Indexing is in flight: the job is queued, or the file is so new that
	// queue seeding has not enqueued it yet and (without a stat result) its
	// content type is not yet known.
	PreviewStatus_PREVIEW_STATUS_PENDING PreviewStatus = 2
	// An indexer holds the job right now.
	PreviewStatus_PREVIEW_STATUS_PROCESSING PreviewStatus = 3
	// preview_key is set; the preview is ready to serve.
	PreviewStatus_PREVIEW_STATUS_READY PreviewStatus = 4
	// Indexing attempts are exhausted; the job is parked as error until
	// manually reset.
	PreviewStatus_PREVIEW_STATUS_FAILED PreviewStatus = 5
)

// Enum value maps for PreviewStatus.
var (
	PreviewStatus_name = map[int32]string{
		0: "PREVIEW_STATUS_UNSPECIFIED",
		1: "PREVIEW_STATUS_NONE",
		2: "PREVIEW_STATUS_PENDING",
		3: "PREVIEW_STATUS_PROCESSING",
		4: "PREVIEW_STATUS_READY",
		5: "PREVIEW_STATUS_FAILED",
	}
	PreviewStatus_value = map[string]int32{
		"PREVIEW_STATUS_UNSPECIFIED": 0,
		"PREVIEW_STATUS_NONE":        1,
		"PREVIEW_STATUS_PENDING":     2,
		"PREVIEW_STATUS_PROCESSING":  3,
		"PREVIEW_STATUS_READY":       4,
		"PREVIEW_STATUS_FAILED":      5,
	}
)

func (x PreviewStatus) Enum() *PreviewStatus {
	p := new(PreviewStatus)
	*p = x
	return p
}

func (x PreviewStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreviewStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_service_v1_files_proto_enumTypes[0].Descriptor()
}

func (PreviewStatus) Type() protoreflect.EnumType {
	return &file_service_v1_files_proto_enumTypes[0]
}

func (x PreviewStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreviewStatus.Descriptor instead.
func (PreviewStatus) EnumDescriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{0}
}

type GetDownloadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLRequest) Reset() {
	*x = GetDownloadURLRequest{}
	mi := &file_service_v1_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLRequest) ProtoMessage() {}

func (x *GetDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{0}
}

func (x *GetDownloadURLRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DownloadURLSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadURLSpec) Reset() {
	*x = DownloadURLSpec{}
	mi := &file_service_v1_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadURLSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadURLSpec) ProtoMessage() {}

func (x *DownloadURLSpec) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadURLSpec.ProtoReflect.Descriptor instead.
func (*DownloadURLSpec) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadURLSpec) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DownloadURLSpec) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetDownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrls  []*DownloadURLSpec     `protobuf:"bytes,1,rep,name=download_urls,json=downloadUrls,proto3" json:"download_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLResponse) Reset() {
	*x = GetDownloadURLResponse{}
	mi := &file_service_v1_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLResponse) ProtoMessage() {}

func (x *GetDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{2}
}

func (x *GetDownloadURLResponse) GetDownloadUrls() []*DownloadURLSpec {
	if x != nil {
		return x.DownloadUrls
	}
	return nil
}

type GetPreviewURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreviewURLRequest) Reset() {
	*x = GetPreviewURLRequest{}
	mi := &file_service_v1_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreviewURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreviewURLRequest) ProtoMessage() {}

func (x *GetPreviewURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreviewURLRequest.ProtoReflect.Descriptor instead.
func (*GetPreviewURLRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{3}
}

func (x *GetPreviewURLRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type PreviewURLSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewURLSpec) Reset() {
	*x = PreviewURLSpec{}
	mi := &file_service_v1_files_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewURLSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewURLSpec) ProtoMessage() {}

func (x *PreviewURLSpec) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewURLSpec.ProtoReflect.Descriptor instead.
func (*PreviewURLSpec) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{4}
}

func (x *PreviewURLSpec) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PreviewURLSpec) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetPreviewURLResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only files that actually have a preview appear here; ids without one are
	// omitted rather than returned with an empty url.
	PreviewUrls   []*PreviewURLSpec `protobuf:"bytes,1,rep,name=preview_urls,json=previewUrls,proto3" json:"preview_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreviewURLResponse) Reset() {
	*x = GetPreviewURLResponse{}
	mi := &file_service_v1_files_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreviewURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreviewURLResponse) ProtoMessage() {}

func (x *GetPreviewURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreviewURLResponse.ProtoReflect.Descriptor instead.
func (*GetPreviewURLResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{5}
}

func (x *GetPreviewURLResponse) GetPreviewUrls() []*PreviewURLSpec {
	if x != nil {
		return x.PreviewUrls
	}
	return nil
}

type GetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoRequest) Reset() {
	*x = GetFileInfoRequest{}
	mi := &file_service_v1_files_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoRequest) ProtoMessage() {}

func (x *GetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FileInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key         string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ContentType string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes   int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Object key of the generated preview image. Empty when the file has no
	// preview: it is not an image, or the preview index has not run yet.
	PreviewKey string `protobuf:"bytes,7,opt,name=preview_key,json=previewKey,proto3" json:"preview_key,omitempty"`
	// Dimensions of the preview image; zero when preview_key is empty. Aspect
	// ratio is preserved and sources are never upscaled, so these vary per file.
	PreviewWidth  int32 `protobuf:"varint,8,opt,name=preview_width,json=previewWidth,proto3" json:"preview_width,omitempty"`
	PreviewHeight int32 `protobuf:"varint,9,opt,name=preview_height,json=previewHeight,proto3" json:"preview_height,omitempty"`
	// EXIF/XMP metadata, present only for image/camera-RAW files that carry at
	// least one of the two. Unset when the file has no exif index result yet,
	// or has neither EXIF nor XMP data.
	Exif *ExifMetadata `protobuf:"bytes,10,opt,name=exif,proto3" json:"exif,omitempty"`
	// Where this file stands in the preview index pipeline, so clients can
	// distinguish "no preview is coming" from "not yet indexed" — both surface
	// as an empty preview_key. Computed from the index queue by SearchService
	// list RPCs; UNSPECIFIED from RPCs that do not compute it.
	PreviewStatus PreviewStatus `protobuf:"varint,11,opt,name=preview_status,json=previewStatus,proto3,enum=service.v1.PreviewStatus" json:"preview_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_service_v1_files_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{7}
}

func (x *FileInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FileInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FileInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *FileInfo) GetPreviewKey() string {
	if x != nil {
		return x.PreviewKey
	}
	return ""
}

func (x *FileInfo) GetPreviewWidth() int32 {
	if x != nil {
		return x.PreviewWidth
	}
	return 0
}

func (x *FileInfo) GetPreviewHeight() int32 {
	if x != nil {
		return x.PreviewHeight
	}
	return 0
}

func (x *FileInfo) GetExif() *ExifMetadata {
	if x != nil {
		return x.Exif
	}
	return nil
}

func (x *FileInfo) GetPreviewStatus() PreviewStatus {
	if x != nil {
		return x.PreviewStatus
	}
	return PreviewStatus_PREVIEW_STATUS_UNSPECIFIED
}

// EXIF and XMP metadata extracted from an image or camera-RAW file. Mirrors
// internal/db/migrations/003_exif.sql; every field is optional because
// EXIF/XMP tags are sparse (most cameras omit most tags) and absence must be
// distinguishable from a legitimate zero value.
type ExifMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sniffed image type from the metadata parser (e.g. "image/x-canon-cr2"),
	// which may differ from FileInfo.content_type as reported by S3.
	ImageType    *string `protobuf:"bytes,1,opt,name=image_type,json=imageType,proto3,oneof" json:"image_type,omitempty"`
	CameraMake   *string `protobuf:"bytes,2,opt,name=camera_make,json=cameraMake,proto3,oneof" json:"camera_make,omitempty"`
	CameraModel  *string `protobuf:"bytes,3,opt,name=camera_model,json=cameraModel,proto3,oneof" json:"camera_model,omitempty"`
	CameraSerial *string `protobuf:"bytes,4,opt,name=camera_serial,json=cameraSerial,proto3,oneof" json:"camera_serial,omitempty"`
	LensMake     *string `protobuf:"bytes,5,opt,name=lens_make,json=lensMake,proto3,oneof" json:"lens_make,omitempty"`
	LensModel    *string `protobuf:"bytes,6,opt,name=lens_model,json=lensModel,proto3,oneof" json:"lens_model,omitempty"`
	// Naive (zone-less) local capture time as recorded by the camera clock.
	// EXIF DateTimeOriginal carries no offset, so no timezone is attached.
	TakenAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	Iso              *int32                 `protobuf:"varint,8,opt,name=iso,proto3,oneof" json:"iso,omitempty"`
	FNumber          *float32               `protobuf:"fixed32,9,opt,name=f_number,json=fNumber,proto3,oneof" json:"f_number,omitempty"`
	ExposureTime     *float32               `protobuf:"fixed32,10,opt,name=exposure_time,json=exposureTime,proto3,oneof" json:"exposure_time,omitempty"`            // seconds
	FocalLength      *float32               `protobuf:"fixed32,11,opt,name=focal_length,json=focalLength,proto3,oneof" json:"focal_length,omitempty"`               // millimeters
	FocalLength_35Mm *float32               `protobuf:"fixed32,12,opt,name=focal_length_35mm,json=focalLength35mm,proto3,oneof" json:"focal_length_35mm,omitempty"` // millimeters, 35mm-equivalent
	ExposureProgram  *int32                 `protobuf:"varint,13,opt,name=exposure_program,json=exposureProgram,proto3,oneof" json:"exposure_program,omitempty"`
	MeteringMode     *int32                 `protobuf:"varint,14,opt,name=metering_mode,json=meteringMode,proto3,oneof" json:"metering_mode,omitempty"`
	Flash            *int32                 `protobuf:"varint,15,opt,name=flash,proto3,oneof" json:"flash,omitempty"`
	Orientation      *int32                 `protobuf:"varint,16,opt,name=orientation,proto3,oneof" json:"orientation,omitempty"`
	ImageWidth       *int32                 `protobuf:"varint,17,opt,name=image_width,json=imageWidth,proto3,oneof" json:"image_width,omitempty"`
	ImageHeight      *int32                 `protobuf:"varint,18,opt,name=image_height,json=imageHeight,proto3,oneof" json:"image_height,omitempty"`
	// GPS, kept at full precision (private, single-tenant bucket).
	GpsLatitude  *float64 `protobuf:"fixed64,19,opt,name=gps_latitude,json=gpsLatitude,proto3,oneof" json:"gps_latitude,omitempty"`
	GpsLongitude *float64 `protobuf:"fixed64,20,opt,name=gps_longitude,json=gpsLongitude,proto3,oneof" json:"gps_longitude,omitempty"`
	GpsAltitude  *float32 `protobuf:"fixed32,21,opt,name=gps_altitude,json=gpsAltitude,proto3,oneof" json:"gps_altitude,omitempty"`
	// Unlike taken_at, GPS timestamps are unambiguously UTC per the EXIF spec.
	GpsAt            *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=gps_at,json=gpsAt,proto3" json:"gps_at,omitempty"`
	Software         *string                `protobuf:"bytes,23,opt,name=software,proto3,oneof" json:"software,omitempty"`
	Artist           *string                `protobuf:"bytes,24,opt,name=artist,proto3,oneof" json:"artist,omitempty"`
	Copyright        *string                `protobuf:"bytes,25,opt,name=copyright,proto3,oneof" json:"copyright,omitempty"`
	ImageDescription *string                `protobuf:"bytes,26,opt,name=image_description,json=imageDescription,proto3,oneof" json:"image_description,omitempty"`
	XmpTitle         *string                `protobuf:"bytes,27,opt,name=xmp_title,json=xmpTitle,proto3,oneof" json:"xmp_title,omitempty"`
	XmpDescription   *string                `protobuf:"bytes,28,opt,name=xmp_description,json=xmpDescription,proto3,oneof" json:"xmp_description,omitempty"`
	XmpCreator       *string                `protobuf:"bytes,29,opt,name=xmp_creator,json=xmpCreator,proto3,oneof" json:"xmp_creator,omitempty"`
	XmpLabel         *string                `protobuf:"bytes,30,opt,name=xmp_label,json=xmpLabel,proto3,oneof" json:"xmp_label,omitempty"`
	XmpRating        *int32                 `protobuf:"varint,31,opt,name=xmp_rating,json=xmpRating,proto3,oneof" json:"xmp_rating,omitempty"`
	XmpKeywords      []string               `protobuf:"bytes,32,rep,name=xmp_keywords,json=xmpKeywords,proto3" json:"xmp_keywords,omitempty"`
	// XMP xmp:CreateDate carries a zone offset, unlike taken_at.
	XmpCreateDate *timestamppb.Timestamp `protobuf:"bytes,33,opt,name=xmp_create_date,json=xmpCreateDate,proto3" json:"xmp_create_date,omitempty"`
	// Which of EXIF/XMP contributed to this metadata, so an absent field can
	// be told apart from "no EXIF/XMP block was present at all".
	HasExif       bool `protobuf:"varint,34,opt,name=has_exif,json=hasExif,proto3" json:"has_exif,omitempty"`
	HasXmp        bool `protobuf:"varint,35,opt,name=has_xmp,json=hasXmp,proto3" json:"has_xmp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExifMetadata) Reset() {
	*x = ExifMetadata{}
	mi := &file_service_v1_files_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExifMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExifMetadata) ProtoMessage() {}

func (x *ExifMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExifMetadata.ProtoReflect.Descriptor instead.
func (*ExifMetadata) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{8}
}

func (x *ExifMetadata) GetImageType() string {
	if x != nil && x.ImageType != nil {
		return *x.ImageType
	}
	return ""
}

func (x *ExifMetadata) GetCameraMake() string {
	if x != nil && x.CameraMake != nil {
		return *x.CameraMake
	}
	return ""
}

func (x *ExifMetadata) GetCameraModel() string {
	if x != nil && x.CameraModel != nil {
		return *x.CameraModel
	}
	return ""
}

func (x *ExifMetadata) GetCameraSerial() string {
	if x != nil && x.CameraSerial != nil {
		return *x.CameraSerial
	}
	return ""
}

func (x *ExifMetadata) GetLensMake() string {
	if x != nil && x.LensMake != nil {
		return *x.LensMake
	}
	return ""
}

func (x *ExifMetadata) GetLensModel() string {
	if x != nil && x.LensModel != nil {
		return *x.LensModel
	}
	return ""
}

func (x *ExifMetadata) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *ExifMetadata) GetIso() int32 {
	if x != nil && x.Iso != nil {
		return *x.Iso
	}
	return 0
}

func (x *ExifMetadata) GetFNumber() float32 {
	if x != nil && x.FNumber != nil {
		return *x.FNumber
	}
	return 0
}

func (x *ExifMetadata) GetExposureTime() float32 {
	if x != nil && x.ExposureTime != nil {
		return *x.ExposureTime
	}
	return 0
}

func (x *ExifMetadata) GetFocalLength() float32 {
	if x != nil && x.FocalLength != nil {
		return *x.FocalLength
	}
	return 0
}

func (x *ExifMetadata) GetFocalLength_35Mm() float32 {
	if x != nil && x.FocalLength_35Mm != nil {
		return *x.FocalLength_35Mm
	}
	return 0
}

func (x *ExifMetadata) GetExposureProgram() int32 {
	if x != nil && x.ExposureProgram != nil {
		return *x.ExposureProgram
	}
	return 0
}

func (x *ExifMetadata) GetMeteringMode() int32 {
	if x != nil && x.MeteringMode != nil {
		return *x.MeteringMode
	}
	return 0
}

func (x *ExifMetadata) GetFlash() int32 {
	if x != nil && x.Flash != nil {
		return *x.Flash
	}
	return 0
}

func (x *ExifMetadata) GetOrientation() int32 {
	if x != nil && x.Orientation != nil {
		return *x.Orientation
	}
	return 0
}

func (x *ExifMetadata) GetImageWidth() int32 {
	if x != nil && x.ImageWidth != nil {
		return *x.ImageWidth
	}
	return 0
}

func (x *ExifMetadata) GetImageHeight() int32 {
	if x != nil && x.ImageHeight != nil {
		return *x.ImageHeight
	}
	return 0
}

func (x *ExifMetadata) GetGpsLatitude() float64 {
	if x != nil && x.GpsLatitude != nil {
		return *x.GpsLatitude
	}
	return 0
}

func (x *ExifMetadata) GetGpsLongitude() float64 {
	if x != nil && x.GpsLongitude != nil {
		return *x.GpsLongitude
	}
	return 0
}

func (x *ExifMetadata) GetGpsAltitude() float32 {
	if x != nil && x.GpsAltitude != nil {
		return *x.GpsAltitude
	}
	return 0
}

func (x *ExifMetadata) GetGpsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GpsAt
	}
	return nil
}

func (x *ExifMetadata) GetSoftware() string {
	if x != nil && x.Software != nil {
		return *x.Software
	}
	return ""
}

func (x *ExifMetadata) GetArtist() string {
	if x != nil && x.Artist != nil {
		return *x.Artist
	}
	return ""
}

func (x *ExifMetadata) GetCopyright() string {
	if x != nil && x.Copyright != nil {
		return *x.Copyright
	}
	return ""
}

func (x *ExifMetadata) GetImageDescription() string {
	if x != nil && x.ImageDescription != nil {
		return *x.ImageDescription
	}
	return ""
}

func (x *ExifMetadata) GetXmpTitle() string {
	if x != nil && x.XmpTitle != nil {
		return *x.XmpTitle
	}
	return ""
}

func (x *ExifMetadata) GetXmpDescription() string {
	if x != nil && x.XmpDescription != nil {
		return *x.XmpDescription
	}
	return ""
}

func (x *ExifMetadata) GetXmpCreator() string {
	if x != nil && x.XmpCreator != nil {
		return *x.XmpCreator
	}
	return ""
}

func (x *ExifMetadata) GetXmpLabel() string {
	if x != nil && x.XmpLabel != nil {
		return *x.XmpLabel
	}
	return ""
}

func (x *ExifMetadata) GetXmpRating() int32 {
	if x != nil && x.XmpRating != nil {
		return *x.XmpRating
	}
	return 0
}

func (x *ExifMetadata) GetXmpKeywords() []string {
	if x != nil {
		return x.XmpKeywords
	}
	return nil
}

func (x *ExifMetadata) GetXmpCreateDate() *timestamppb.Timestamp {
	if x != nil {
		return x.XmpCreateDate
	}
	return nil
}

func (x *ExifMetadata) GetHasExif() bool {
	if x != nil {
		return x.HasExif
	}
	return false
}

func (x *ExifMetadata) GetHasXmp() bool {
	if x != nil {
		return x.HasXmp
	}
	return false
}

type GetFileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoResponse) Reset() {
	*x = GetFileInfoResponse{}
	mi := &file_service_v1_files_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoResponse) ProtoMessage() {}

func (x *GetFileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoResponse.ProtoReflect.Descriptor instead.
func (*GetFileInfoResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{9}
}

func (x *GetFileInfoResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_service_v1_files_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteFileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_service_v1_files_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{11}
}

type GetUploadURLRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination object key. The client sets its own Content-Type header on
	// the PUT; CommitUpload re-stats the object afterward rather than trusting
	// anything about the upload, so it is not threaded through here.
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadURLRequest) Reset() {
	*x = GetUploadURLRequest{}
	mi := &file_service_v1_files_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLRequest) ProtoMessage() {}

func (x *GetUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GetUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{12}
}

func (x *GetUploadURLRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetUploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadURLResponse) Reset() {
	*x = GetUploadURLResponse{}
	mi := &file_service_v1_files_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLResponse) ProtoMessage() {}

func (x *GetUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLResponse.ProtoReflect.Descriptor instead.
func (*GetUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{13}
}

func (x *GetUploadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CommitUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key the client PUT its bytes to via the GetUploadURL URL.
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitUploadRequest) Reset() {
	*x = CommitUploadRequest{}
	mi := &file_service_v1_files_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadRequest) ProtoMessage() {}

func (x *CommitUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitUploadRequest.ProtoReflect.Descriptor instead.
func (*CommitUploadRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{14}
}

func (x *CommitUploadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CommitUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stat-derived record for the newly-landed object. Indexing (previews,
	// EXIF, etc.) is asynchronous — this reflects only what S3 knows
	// immediately, not full FileInfo.
	File          *FileInfo `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitUploadResponse) Reset() {
	*x = CommitUploadResponse{}
	mi := &file_service_v1_files_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadResponse) ProtoMessage() {}

func (x *CommitUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitUploadResponse.ProtoReflect.Descriptor instead.
func (*CommitUploadResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{15}
}

func (x *CommitUploadResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type GetDirectoryStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory prefix; must end in "/" (validated server-side) so a prefix
	// like "docs" can never match "docs-archive/" too.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoryStatsRequest) Reset() {
	*x = GetDirectoryStatsRequest{}
	mi := &file_service_v1_files_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoryStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryStatsRequest) ProtoMessage() {}

func (x *GetDirectoryStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDirectoryStatsRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{16}
}

func (x *GetDirectoryStatsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetDirectoryStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileCount     int64                  `protobuf:"varint,1,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoryStatsResponse) Reset() {
	*x = GetDirectoryStatsResponse{}
	mi := &file_service_v1_files_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoryStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryStatsResponse) ProtoMessage() {}

func (x *GetDirectoryStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryStatsResponse.ProtoReflect.Descriptor instead.
func (*GetDirectoryStatsResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{17}
}

func (x *GetDirectoryStatsResponse) GetFileCount() int64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *GetDirectoryStatsResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type DeleteDirectoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Same validation as GetDirectoryStats.path. There is no dry-run flag:
	// callers are expected to show GetDirectoryStats' counts in a confirm
	// dialog first (see web/src/components/Browser.tsx's delete-folder flow).
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDirectoryRequest) Reset() {
	*x = DeleteDirectoryRequest{}
	mi := &file_service_v1_files_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDirectoryRequest) ProtoMessage() {}

func (x *DeleteDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDirectoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteDirectoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of files actually removed (S3 object + DB row both succeeded)
	// before either finishing or hitting an error. Not atomic: on error, some
	// prefix of the directory's files may already be gone while the rest
	// remain — retry with the same path to continue, S3 no-ops keys already
	// deleted.
	DeletedCount  int64 `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDirectoryResponse) Reset() {
	*x = DeleteDirectoryResponse{}
	mi := &file_service_v1_files_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDirectoryResponse) ProtoMessage() {}

func (x *DeleteDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_files_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDirectoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_files_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteDirectoryResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

var File_service_v1_files_proto protoreflect.FileDescriptor

const file_service_v1_files_proto_rawDesc = "" +
	"\n" +
	"\x16service/v1/files.proto\x12\n" +
	"service.v1\x1a\x1fgoogle/protobuf/timestamp.proto\")\n" +
	"\x15GetDownloadURLRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"3\n" +
	"\x0fDownloadURLSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"Z\n" +
	"\x16GetDownloadURLResponse\x12@\n" +
	"\rdownload_urls\x18\x01 \x03(\v2\x1b.service.v1.DownloadURLSpecR\fdownloadUrls\"(\n" +
	"\x14GetPreviewURLRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"2\n" +
	"\x0ePreviewURLSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"V\n" +
	"\x15GetPreviewURLResponse\x12=\n" +
	"\fpreview_urls\x18\x01 \x03(\v2\x1a.service.v1.PreviewURLSpecR\vpreviewUrls\"$\n" +
	"\x12GetFileInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc1\x03\n" +
	"\bFileInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vpreview_key\x18\a \x01(\tR\n" +
	"previewKey\x12#\n" +
	"\rpreview_width\x18\b \x01(\x05R\fpreviewWidth\x12%\n" +
	"\x0epreview_height\x18\t \x01(\x05R\rpreviewHeight\x12,\n" +
	"\x04exif\x18\n" +
	" \x01(\v2\x18.service.v1.ExifMetadataR\x04exif\x12@\n" +
	"\x0epreview_status\x18\v \x01(\x0e2\x19.service.v1.PreviewStatusR\rpreviewStatus\"\xb0\x0e\n" +
	"\fExifMetadata\x12\"\n" +
	"\n" +
	"image_type\x18\x01 \x01(\tH\x00R\timageType\x88\x01\x01\x12$\n" +
	"\vcamera_make\x18\x02 \x01(\tH\x01R\n" +
	"cameraMake\x88\x01\x01\x12&\n" +
	"\fcamera_model\x18\x03 \x01(\tH\x02R\vcameraModel\x88\x01\x01\x12(\n" +
	"\rcamera_serial\x18\x04 \x01(\tH\x03R\fcameraSerial\x88\x01\x01\x12 \n" +
	"\tlens_make\x18\x05 \x01(\tH\x04R\blensMake\x88\x01\x01\x12\"\n" +
	"\n" +
	"lens_model\x18\x06 \x01(\tH\x05R\tlensModel\x88\x01\x01\x125\n" +
	"\btaken_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12\x15\n" +
	"\x03iso\x18\b \x01(\x05H\x06R\x03iso\x88\x01\x01\x12\x1e\n" +
	"\bf_number\x18\t \x01(\x02H\aR\afNumber\x88\x01\x01\x12(\n" +
	"\rexposure_time\x18\n" +
	" \x01(\x02H\bR\fexposureTime\x88\x01\x01\x12&\n" +
	"\ffocal_length\x18\v \x01(\x02H\tR\vfocalLength\x88\x01\x01\x12/\n" +
	"\x11focal_length_35mm\x18\f \x01(\x02H\n" +
	"R\x0ffocalLength35mm\x88\x01\x01\x12.\n" +
	"\x10exposure_program\x18\r \x01(\x05H\vR\x0fexposureProgram\x88\x01\x01\x12(\n" +
	"\rmetering_mode\x18\x0e \x01(\x05H\fR\fmeteringMode\x88\x01\x01\x12\x19\n" +
	"\x05flash\x18\x0f \x01(\x05H\rR\x05flash\x88\x01\x01\x12%\n" +
	"\vorientation\x18\x10 \x01(\x05H\x0eR\vorientation\x88\x01\x01\x12$\n" +
	"\vimage_width\x18\x11 \x01(\x05H\x0fR\n" +
	"imageWidth\x88\x01\x01\x12&\n" +
	"\fimage_height\x18\x12 \x01(\x05H\x10R\vimageHeight\x88\x01\x01\x12&\n" +
	"\fgps_latitude\x18\x13 \x01(\x01H\x11R\vgpsLatitude\x88\x01\x01\x12(\n" +
	"\rgps_longitude\x18\x14 \x01(\x01H\x12R\fgpsLongitude\x88\x01\x01\x12&\n" +
	"\fgps_altitude\x18\x15 \x01(\x02H\x13R\vgpsAltitude\x88\x01\x01\x121\n" +
	"\x06gps_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\x05gpsAt\x12\x1f\n" +
	"\bsoftware\x18\x17 \x01(\tH\x14R\bsoftware\x88\x01\x01\x12\x1b\n" +
	"\x06artist\x18\x18 \x01(\tH\x15R\x06artist\x88\x01\x01\x12!\n" +
	"\tcopyright\x18\x19 \x01(\tH\x16R\tcopyright\x88\x01\x01\x120\n" +
	"\x11image_description\x18\x1a \x01(\tH\x17R\x10imageDescription\x88\x01\x01\x12 \n" +
	"\txmp_title\x18\x1b \x01(\tH\x18R\bxmpTitle\x88\x01\x01\x12,\n" +
	"\x0fxmp_description\x18\x1c \x01(\tH\x19R\x0exmpDescription\x88\x01\x01\x12$\n" +
	"\vxmp_creator\x18\x1d \x01(\tH\x1aR\n" +
	"xmpCreator\x88\x01\x01\x12 \n" +
	"\txmp_label\x18\x1e \x01(\tH\x1bR\bxmpLabel\x88\x01\x01\x12\"\n" +
	"\n" +
	"xmp_rating\x18\x1f \x01(\x05H\x1cR\txmpRating\x88\x01\x01\x12!\n" +
	"\fxmp_keywords\x18  \x03(\tR\vxmpKeywords\x12B\n" +
	"\x0fxmp_create_date\x18! \x01(\v2\x1a.google.protobuf.TimestampR\rxmpCreateDate\x12\x19\n" +
	"\bhas_exif\x18\" \x01(\bR\ahasExif\x12\x17\n" +
	"\ahas_xmp\x18# \x01(\bR\x06hasXmpB\r\n" +
	"\v_image_typeB\x0e\n" +
	"\f_camera_makeB\x0f\n" +
	"\r_camera_modelB\x10\n" +
	"\x0e_camera_serialB\f\n" +
	"\n" +
	"_lens_makeB\r\n" +
	"\v_lens_modelB\x06\n" +
	"\x04_isoB\v\n" +
	"\t_f_numberB\x10\n" +
	"\x0e_exposure_timeB\x0f\n" +
	"\r_focal_lengthB\x14\n" +
	"\x12_focal_length_35mmB\x13\n" +
	"\x11_exposure_programB\x10\n" +
	"\x0e_metering_modeB\b\n" +
	"\x06_flashB\x0e\n" +
	"\f_orientationB\x0e\n" +
	"\f_image_widthB\x0f\n" +
	"\r_image_heightB\x0f\n" +
	"\r_gps_latitudeB\x10\n" +
	"\x0e_gps_longitudeB\x0f\n" +
	"\r_gps_altitudeB\v\n" +
	"\t_softwareB\t\n" +
	"\a_artistB\f\n" +
	"\n" +
	"_copyrightB\x14\n" +
	"\x12_image_descriptionB\f\n" +
	"\n" +
	"_xmp_titleB\x12\n" +
	"\x10_xmp_descriptionB\x0e\n" +
	"\f_xmp_creatorB\f\n" +
	"\n" +
	"_xmp_labelB\r\n" +
	"\v_xmp_rating\"?\n" +
	"\x13GetFileInfoResponse\x12(\n" +
	"\x04file\x18\x01 \x01(\v2\x14.service.v1.FileInfoR\x04file\"#\n" +
	"\x11DeleteFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteFileResponse\"'\n" +
	"\x13GetUploadURLRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"(\n" +
	"\x14GetUploadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"'\n" +
	"\x13CommitUploadRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"@\n" +
	"\x14CommitUploadResponse\x12(\n" +
	"\x04file\x18\x01 \x01(\v2\x14.service.v1.FileInfoR\x04file\".\n" +
	"\x18GetDirectoryStatsRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"[\n" +
	"\x19GetDirectoryStatsResponse\x12\x1d\n" +
	"\n" +
	"file_count\x18\x01 \x01(\x03R\tfileCount\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\",\n" +
	"\x16DeleteDirectoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\">\n" +
	"\x17DeleteDirectoryResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x03R\fdeletedCount*\xb8\x01\n" +
	"\rPreviewStatus\x12\x1e\n" +
	"\x1aPREVIEW_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PREVIEW_STATUS_NONE\x10\x01\x12\x1a\n" +
	"\x16PREVIEW_STATUS_PENDING\x10\x02\x12\x1d\n" +
	"\x19PREVIEW_STATUS_PROCESSING\x10\x03\x12\x18\n" +
	"\x14PREVIEW_STATUS_READY\x10\x04\x12\x19\n" +
	"\x15PREVIEW_STATUS_FAILED\x10\x052\xbe\x05\n" +
	"\fFilesService\x12W\n" +
	"\x0eGetDownloadURL\x12!.service.v1.GetDownloadURLRequest\x1a\".service.v1.GetDownloadURLResponse\x12T\n" +
	"\rGetPreviewURL\x12 .service.v1.GetPreviewURLRequest\x1a!.service.v1.GetPreviewURLResponse\x12N\n" +
	"\vGetFileInfo\x12\x1e.service.v1.GetFileInfoRequest\x1a\x1f.service.v1.GetFileInfoResponse\x12K\n" +
	"\n" +
	"DeleteFile\x12\x1d.service.v1.DeleteFileRequest\x1a\x1e.service.v1.DeleteFileResponse\x12Q\n" +
	"\fGetUploadURL\x12\x1f.service.v1.GetUploadURLRequest\x1a .service.v1.GetUploadURLResponse\x12Q\n" +
	"\fCommitUpload\x12\x1f.service.v1.CommitUploadRequest\x1a .service.v1.CommitUploadResponse\x12`\n" +
	"\x11GetDirectoryStats\x12$.service.v1.GetDirectoryStatsRequest\x1a%.service.v1.GetDirectoryStatsResponse\x12Z\n" +
	"\x0fDeleteDirectory\x12\".service.v1.DeleteDirectoryRequest\x1a#.service.v1.DeleteDirectoryResponseB(Z&file-indexer/internal/pb/service/v1;pbb\x06proto3"

var (
	file_service_v1_files_proto_rawDescOnce sync.Once
	file_service_v1_files_proto_rawDescData []byte
)

func file_service_v1_files_proto_rawDescGZIP() []byte {
	file_service_v1_files_proto_rawDescOnce.Do(func() {
		file_service_v1_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_v1_files_proto_rawDesc), len(file_service_v1_files_proto_rawDesc)))
	})
	return file_service_v1_files_proto_rawDescData
}

var file_service_v1_files_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_v1_files_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_service_v1_files_proto_goTypes = []any{
	(PreviewStatus)(0),                // 0: service.v1.PreviewStatus
	(*GetDownloadURLRequest)(nil),     // 1: service.v1.GetDownloadURLRequest
	(*DownloadURLSpec)(nil),           // 2: service.v1.DownloadURLSpec
	(*GetDownloadURLResponse)(nil),    // 3: service.v1.GetDownloadURLResponse
	(*GetPreviewURLRequest)(nil),      // 4: service.v1.GetPreviewURLRequest
	(*PreviewURLSpec)(nil),            // 5: service.v1.PreviewURLSpec
	(*GetPreviewURLResponse)(nil),     // 6: service.v1.GetPreviewURLResponse
	(*GetFileInfoRequest)(nil),        // 7: service.v1.GetFileInfoRequest
	(*FileInfo)(nil),                  // 8: service.v1.FileInfo
	(*ExifMetadata)(nil),              // 9: service.v1.ExifMetadata
	(*GetFileInfoResponse)(nil),       // 10: service.v1.GetFileInfoResponse
	(*DeleteFileRequest)(nil),         // 11: service.v1.DeleteFileRequest
	(*DeleteFileResponse)(nil),        // 12: service.v1.DeleteFileResponse
	(*GetUploadURLRequest)(nil),       // 13: service.v1.GetUploadURLRequest
	(*GetUploadURLResponse)(nil),      // 14: service.v1.GetUploadURLResponse
	(*CommitUploadRequest)(nil),       // 15: service.v1.CommitUploadRequest
	(*CommitUploadResponse)(nil),      // 16: service.v1.CommitUploadResponse
	(*GetDirectoryStatsRequest)(nil),  // 17: service.v1.GetDirectoryStatsRequest
	(*GetDirectoryStatsResponse)(nil), // 18: service.v1.GetDirectoryStatsResponse
	(*DeleteDirectoryRequest)(nil),    // 19: service.v1.DeleteDirectoryRequest
	(*DeleteDirectoryResponse)(nil),   // 20: service.v1.DeleteDirectoryResponse
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
}
var file_service_v1_files_proto_depIdxs = []int32{
	2,  // 0: service.v1.GetDownloadURLResponse.download_urls:type_name -> service.v1.DownloadURLSpec
	5,  // 1: service.v1.GetPreviewURLResponse.preview_urls:type_name -> service.v1.PreviewURLSpec
	21, // 2: service.v1.FileInfo.created_at:type_name -> google.protobuf.Timestamp
	21, // 3: service.v1.FileInfo.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 4: service.v1.FileInfo.exif:type_name -> service.v1.ExifMetadata
	0,  // 5: service.v1.FileInfo.preview_status:type_name -> service.v1.PreviewStatus
	21, // 6: service.v1.ExifMetadata.taken_at:type_name -> google.protobuf.Timestamp
	21, // 7: service.v1.ExifMetadata.gps_at:type_name -> google.protobuf.Timestamp
	21, // 8: service.v1.ExifMetadata.xmp_create_date:type_name -> google.protobuf.Timestamp
	8,  // 9: service.v1.GetFileInfoResponse.file:type_name -> service.v1.FileInfo
	8,  // 10: service.v1.CommitUploadResponse.file:type_name -> service.v1.FileInfo
	1,  // 11: service.v1.FilesService.GetDownloadURL:input_type -> service.v1.GetDownloadURLRequest
	4,  // 12: service.v1.FilesService.GetPreviewURL:input_type -> service.v1.GetPreviewURLRequest
	7,  // 13: service.v1.FilesService.GetFileInfo:input_type -> service.v1.GetFileInfoRequest
	11, // 14: service.v1.FilesService.DeleteFile:input_type -> service.v1.DeleteFileRequest
	13, // 15: service.v1.FilesService.GetUploadURL:input_type -> service.v1.GetUploadURLRequest
	15, // 16: service.v1.FilesService.CommitUpload:input_type -> service.v1.CommitUploadRequest
	17, // 17: service.v1.FilesService.GetDirectoryStats:input_type -> service.v1.GetDirectoryStatsRequest
	19, // 18: service.v1.FilesService.DeleteDirectory:input_type -> service.v1.DeleteDirectoryRequest
	3,  // 19: service.v1.FilesService.GetDownloadURL:output_type -> service.v1.GetDownloadURLResponse
	6,  // 20: service.v1.FilesService.GetPreviewURL:output_type -> service.v1.GetPreviewURLResponse
	10, // 21: service.v1.FilesService.GetFileInfo:output_type -> service.v1.GetFileInfoResponse
	12, // 22: service.v1.FilesService.DeleteFile:output_type -> service.v1.DeleteFileResponse
	14, // 23: service.v1.FilesService.GetUploadURL:output_type -> service.v1.GetUploadURLResponse
	16, // 24: service.v1.FilesService.CommitUpload:output_type -> service.v1.CommitUploadResponse
	18, // 25: service.v1.FilesService.GetDirectoryStats:output_type -> service.v1.GetDirectoryStatsResponse
	20, // 26: service.v1.FilesService.DeleteDirectory:output_type -> service.v1.DeleteDirectoryResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_service_v1_files_proto_init() }
func file_service_v1_files_proto_init() {
	if File_service_v1_files_proto != nil {
		return
	}
	file_service_v1_files_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_v1_files_proto_rawDesc), len(file_service_v1_files_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_v1_files_proto_goTypes,
		DependencyIndexes: file_service_v1_files_proto_depIdxs,
		EnumInfos:         file_service_v1_files_proto_enumTypes,
		MessageInfos:      file_service_v1_files_proto_msgTypes,
	}.Build()
	File_service_v1_files_proto = out.File
	file_service_v1_files_proto_goTypes = nil
	file_service_v1_files_proto_depIdxs = nil
}
