// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: service/v1/indexer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *FileRef               `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_service_v1_indexer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_indexer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *IndexRequest) GetRef() *FileRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type FileRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRef) Reset() {
	*x = FileRef{}
	mi := &file_service_v1_indexer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRef) ProtoMessage() {}

func (x *FileRef) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_indexer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRef.ProtoReflect.Descriptor instead.
func (*FileRef) Descriptor() ([]byte, []int) {
	return file_service_v1_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *FileRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_service_v1_indexer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_indexer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_indexer_proto_rawDescGZIP(), []int{2}
}

func (x *IndexResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_service_v1_indexer_proto protoreflect.FileDescriptor

const file_service_v1_indexer_proto_rawDesc = "" +
	"\n" +
	"\x18service/v1/indexer.proto\x12\n" +
	"service.v1\"5\n" +
	"\fIndexRequest\x12%\n" +
	"\x03ref\x18\x01 \x01(\v2\x13.service.v1.FileRefR\x03ref\"\x1b\n" +
	"\aFileRef\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"'\n" +
	"\rIndexResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2P\n" +
	"\x0eIndexerService\x12>\n" +
	"\x05Index\x12\x18.service.v1.IndexRequest\x1a\x19.service.v1.IndexResponse\"\x00B(Z&file-indexer/internal/pb/service/v1;pbb\x06proto3"

var (
	file_service_v1_indexer_proto_rawDescOnce sync.Once
	file_service_v1_indexer_proto_rawDescData []byte
)

func file_service_v1_indexer_proto_rawDescGZIP() []byte {
	file_service_v1_indexer_proto_rawDescOnce.Do(func() {
		file_service_v1_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_v1_indexer_proto_rawDesc), len(file_service_v1_indexer_proto_rawDesc)))
	})
	return file_service_v1_indexer_proto_rawDescData
}

var file_service_v1_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_v1_indexer_proto_goTypes = []any{
	(*IndexRequest)(nil),  // 0: service.v1.IndexRequest
	(*FileRef)(nil),       // 1: service.v1.FileRef
	(*IndexResponse)(nil), // 2: service.v1.IndexResponse
}
var file_service_v1_indexer_proto_depIdxs = []int32{
	1, // 0: service.v1.IndexRequest.ref:type_name -> service.v1.FileRef
	0, // 1: service.v1.IndexerService.Index:input_type -> service.v1.IndexRequest
	2, // 2: service.v1.IndexerService.Index:output_type -> service.v1.IndexResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_v1_indexer_proto_init() }
func file_service_v1_indexer_proto_init() {
	if File_service_v1_indexer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_v1_indexer_proto_rawDesc), len(file_service_v1_indexer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_v1_indexer_proto_goTypes,
		DependencyIndexes: file_service_v1_indexer_proto_depIdxs,
		MessageInfos:      file_service_v1_indexer_proto_msgTypes,
	}.Build()
	File_service_v1_indexer_proto = out.File
	file_service_v1_indexer_proto_goTypes = nil
	file_service_v1_indexer_proto_depIdxs = nil
}
