// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: service/v1/search.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SortField selects the column ListFiles orders results by.
type SortField int32

const (
	SortField_SORT_FIELD_UNSPECIFIED SortField = 0 // defaults to SORT_FIELD_KEY
	SortField_SORT_FIELD_KEY         SortField = 1
	// Object last-modified time (from the stat index); unset until a file is
	// indexed, sorting those files first ascending.
	SortField_SORT_FIELD_LAST_MODIFIED SortField = 2
	SortField_SORT_FIELD_SIZE          SortField = 3
)

// Enum value maps for SortField.
var (
	SortField_name = map[int32]string{
		0: "SORT_FIELD_UNSPECIFIED",
		1: "SORT_FIELD_KEY",
		2: "SORT_FIELD_LAST_MODIFIED",
		3: "SORT_FIELD_SIZE",
	}
	SortField_value = map[string]int32{
		"SORT_FIELD_UNSPECIFIED":   0,
		"SORT_FIELD_KEY":           1,
		"SORT_FIELD_LAST_MODIFIED": 2,
		"SORT_FIELD_SIZE":          3,
	}
)

func (x SortField) Enum() *SortField {
	p := new(SortField)
	*p = x
	return p
}

func (x SortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortField) Descriptor() protoreflect.EnumDescriptor {
	return file_service_v1_search_proto_enumTypes[0].Descriptor()
}

func (SortField) Type() protoreflect.EnumType {
	return &file_service_v1_search_proto_enumTypes[0]
}

func (x SortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortField.Descriptor instead.
func (SortField) EnumDescriptor() ([]byte, []int) {
	return file_service_v1_search_proto_rawDescGZIP(), []int{0}
}

// SortOrder selects the direction ListFiles orders results in.
type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0 // defaults to SORT_ORDER_ASC
	SortOrder_SORT_ORDER_ASC         SortOrder = 1
	SortOrder_SORT_ORDER_DESC        SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_service_v1_search_proto_enumTypes[1].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_service_v1_search_proto_enumTypes[1]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_service_v1_search_proto_rawDescGZIP(), []int{1}
}

type ListFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of files to return. Defaults to 50, clamped to 200.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous ListFiles call's next_page_token.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to ListFiles (except
	// page_size) must match the call that provided the page token; otherwise
	// the request fails with INVALID_ARGUMENT.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Only return files whose key starts with this prefix.
	Prefix string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Filter by MIME type: an exact match like "image/png", or a category
	// prefix ending in "/" like "image/" to match all images.
	ContentType   string    `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SortField     SortField `protobuf:"varint,5,opt,name=sort_field,json=sortField,proto3,enum=service.v1.SortField" json:"sort_field,omitempty"`
	SortOrder     SortOrder `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3,enum=service.v1.SortOrder" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_service_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *ListFilesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFilesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListFilesRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListFilesRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ListFilesRequest) GetSortField() SortField {
	if x != nil {
		return x.SortField
	}
	return SortField_SORT_FIELD_UNSPECIFIED
}

func (x *ListFilesRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

type ListFilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Files []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	// Cursor for the next page; empty when there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_service_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// ListDirectory lists the immediate children of a directory: subdirectories
// (materialized in a dedicated index kept in sync with every file write —
// see the directories table's doc comment in
// internal/db/migrations/001_initial.sql; a directory "exists" only as long
// as some key lives under it, same as S3 itself) followed by the files
// directly in it. There is no content_type filter here: applying one
// requires per-directory subtree checks that don't fit this index, so a
// client that wants to filter by type should switch to ListFiles from this
// path instead (browsing is navigation; filtering is search).
type ListDirectoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory to list; "" is the bucket root. Normalized to a trailing "/"
	// server-side if the caller omits one.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Maximum number of entries (directories + files combined) to return.
	// Defaults to 50, clamped to 200, same as ListFiles.
	PageSize  int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Sort applies to the files portion only; directories are always
	// alphabetical and always precede files on a given page.
	SortField     SortField `protobuf:"varint,4,opt,name=sort_field,json=sortField,proto3,enum=service.v1.SortField" json:"sort_field,omitempty"`
	SortOrder     SortOrder `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3,enum=service.v1.SortOrder" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryRequest) Reset() {
	*x = ListDirectoryRequest{}
	mi := &file_service_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryRequest) ProtoMessage() {}

func (x *ListDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryRequest.ProtoReflect.Descriptor instead.
func (*ListDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *ListDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListDirectoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDirectoryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListDirectoryRequest) GetSortField() SortField {
	if x != nil {
		return x.SortField
	}
	return SortField_SORT_FIELD_UNSPECIFIED
}

func (x *ListDirectoryRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

type ListDirectoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Immediate child directories, full path from the bucket root, each
	// ending in "/". Always alphabetical, always before files.
	Directories   []string    `protobuf:"bytes,1,rep,name=directories,proto3" json:"directories,omitempty"`
	Files         []*FileInfo `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	NextPageToken string      `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryResponse) Reset() {
	*x = ListDirectoryResponse{}
	mi := &file_service_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryResponse) ProtoMessage() {}

func (x *ListDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryResponse.ProtoReflect.Descriptor instead.
func (*ListDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *ListDirectoryResponse) GetDirectories() []string {
	if x != nil {
		return x.Directories
	}
	return nil
}

func (x *ListDirectoryResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListDirectoryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_service_v1_search_proto protoreflect.FileDescriptor

const file_service_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x17service/v1/search.proto\x12\n" +
	"service.v1\x1a\x16service/v1/files.proto\"\xf5\x01\n" +
	"\x10ListFilesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x124\n" +
	"\n" +
	"sort_field\x18\x05 \x01(\x0e2\x15.service.v1.SortFieldR\tsortField\x124\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x0e2\x15.service.v1.SortOrderR\tsortOrder\"g\n" +
	"\x11ListFilesResponse\x12*\n" +
	"\x05files\x18\x01 \x03(\v2\x14.service.v1.FileInfoR\x05files\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd2\x01\n" +
	"\x14ListDirectoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x124\n" +
	"\n" +
	"sort_field\x18\x04 \x01(\x0e2\x15.service.v1.SortFieldR\tsortField\x124\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x0e2\x15.service.v1.SortOrderR\tsortOrder\"\x8d\x01\n" +
	"\x15ListDirectoryResponse\x12 \n" +
	"\vdirectories\x18\x01 \x03(\tR\vdirectories\x12*\n" +
	"\x05files\x18\x02 \x03(\v2\x14.service.v1.FileInfoR\x05files\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken*n\n" +
	"\tSortField\x12\x1a\n" +
	"\x16SORT_FIELD_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_FIELD_KEY\x10\x01\x12\x1c\n" +
	"\x18SORT_FIELD_LAST_MODIFIED\x10\x02\x12\x13\n" +
	"\x0fSORT_FIELD_SIZE\x10\x03*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x022\xaf\x01\n" +
	"\rSearchService\x12H\n" +
	"\tListFiles\x12\x1c.service.v1.ListFilesRequest\x1a\x1d.service.v1.ListFilesResponse\x12T\n" +
	"\rListDirectory\x12 .service.v1.ListDirectoryRequest\x1a!.service.v1.ListDirectoryResponseB(Z&file-indexer/internal/pb/service/v1;pbb\x06proto3"

var (
	file_service_v1_search_proto_rawDescOnce sync.Once
	file_service_v1_search_proto_rawDescData []byte
)

func file_service_v1_search_proto_rawDescGZIP() []byte {
	file_service_v1_search_proto_rawDescOnce.Do(func() {
		file_service_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_v1_search_proto_rawDesc), len(file_service_v1_search_proto_rawDesc)))
	})
	return file_service_v1_search_proto_rawDescData
}

var file_service_v1_search_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_service_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_v1_search_proto_goTypes = []any{
	(SortField)(0),                // 0: service.v1.SortField
	(SortOrder)(0),                // 1: service.v1.SortOrder
	(*ListFilesRequest)(nil),      // 2: service.v1.ListFilesRequest
	(*ListFilesResponse)(nil),     // 3: service.v1.ListFilesResponse
	(*ListDirectoryRequest)(nil),  // 4: service.v1.ListDirectoryRequest
	(*ListDirectoryResponse)(nil), // 5: service.v1.ListDirectoryResponse
	(*FileInfo)(nil),              // 6: service.v1.FileInfo
}
var file_service_v1_search_proto_depIdxs = []int32{
	0, // 0: service.v1.ListFilesRequest.sort_field:type_name -> service.v1.SortField
	1, // 1: service.v1.ListFilesRequest.sort_order:type_name -> service.v1.SortOrder
	6, // 2: service.v1.ListFilesResponse.files:type_name -> service.v1.FileInfo
	0, // 3: service.v1.ListDirectoryRequest.sort_field:type_name -> service.v1.SortField
	1, // 4: service.v1.ListDirectoryRequest.sort_order:type_name -> service.v1.SortOrder
	6, // 5: service.v1.ListDirectoryResponse.files:type_name -> service.v1.FileInfo
	2, // 6: service.v1.SearchService.ListFiles:input_type -> service.v1.ListFilesRequest
	4, // 7: service.v1.SearchService.ListDirectory:input_type -> service.v1.ListDirectoryRequest
	3, // 8: service.v1.SearchService.ListFiles:output_type -> service.v1.ListFilesResponse
	5, // 9: service.v1.SearchService.ListDirectory:output_type -> service.v1.ListDirectoryResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_service_v1_search_proto_init() }
func file_service_v1_search_proto_init() {
	if File_service_v1_search_proto != nil {
		return
	}
	file_service_v1_files_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_v1_search_proto_rawDesc), len(file_service_v1_search_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_v1_search_proto_goTypes,
		DependencyIndexes: file_service_v1_search_proto_depIdxs,
		EnumInfos:         file_service_v1_search_proto_enumTypes,
		MessageInfos:      file_service_v1_search_proto_msgTypes,
	}.Build()
	File_service_v1_search_proto = out.File
	file_service_v1_search_proto_goTypes = nil
	file_service_v1_search_proto_depIdxs = nil
}
