apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-stat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index-stat
  template:
    metadata:
      labels:
        app: index-stat
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: index-stat
          image: index-stat
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          envFrom:
            - secretRef:
                name: db-secret
            - secretRef:
                name: s3-secret
      volumes:
        - name: tmp
          emptyDir: {}
