apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: files
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: files
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: search
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: search
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: web
