// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package indexer

import (
	"context"
	"file-indexer/internal/db"
	"file-indexer/internal/storage"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQueries creates a new instance of MockQueries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueries(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueries {
	mock := &MockQueries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueries is an autogenerated mock type for the Queries type
type MockQueries struct {
	mock.Mock
}

type MockQueries_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueries) EXPECT() *MockQueries_Expecter {
	return &MockQueries_Expecter{mock: &_m.Mock}
}

// ClaimIndexQueue provides a mock function for the type MockQueries
func (_mock *MockQueries) ClaimIndexQueue(ctx context.Context, arg db.ClaimIndexQueueParams) ([]db.ClaimIndexQueueRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ClaimIndexQueue")
	}

	var r0 []db.ClaimIndexQueueRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ClaimIndexQueueParams) ([]db.ClaimIndexQueueRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ClaimIndexQueueParams) []db.ClaimIndexQueueRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ClaimIndexQueueRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ClaimIndexQueueParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueries_ClaimIndexQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimIndexQueue'
type MockQueries_ClaimIndexQueue_Call struct {
	*mock.Call
}

// ClaimIndexQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ClaimIndexQueueParams
func (_e *MockQueries_Expecter) ClaimIndexQueue(ctx any, arg any) *MockQueries_ClaimIndexQueue_Call {
	return &MockQueries_ClaimIndexQueue_Call{Call: _e.mock.On("ClaimIndexQueue", ctx, arg)}
}

func (_c *MockQueries_ClaimIndexQueue_Call) Run(run func(ctx context.Context, arg db.ClaimIndexQueueParams)) *MockQueries_ClaimIndexQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ClaimIndexQueueParams
		if args[1] != nil {
			arg1 = args[1].(db.ClaimIndexQueueParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueries_ClaimIndexQueue_Call) Return(claimIndexQueueRows []db.ClaimIndexQueueRow, err error) *MockQueries_ClaimIndexQueue_Call {
	_c.Call.Return(claimIndexQueueRows, err)
	return _c
}

func (_c *MockQueries_ClaimIndexQueue_Call) RunAndReturn(run func(ctx context.Context, arg db.ClaimIndexQueueParams) ([]db.ClaimIndexQueueRow, error)) *MockQueries_ClaimIndexQueue_Call {
	_c.Call.Return(run)
	return _c
}

// FailIndexQueue provides a mock function for the type MockQueries
func (_mock *MockQueries) FailIndexQueue(ctx context.Context, arg db.FailIndexQueueParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FailIndexQueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.FailIndexQueueParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueries_FailIndexQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailIndexQueue'
type MockQueries_FailIndexQueue_Call struct {
	*mock.Call
}

// FailIndexQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.FailIndexQueueParams
func (_e *MockQueries_Expecter) FailIndexQueue(ctx any, arg any) *MockQueries_FailIndexQueue_Call {
	return &MockQueries_FailIndexQueue_Call{Call: _e.mock.On("FailIndexQueue", ctx, arg)}
}

func (_c *MockQueries_FailIndexQueue_Call) Run(run func(ctx context.Context, arg db.FailIndexQueueParams)) *MockQueries_FailIndexQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.FailIndexQueueParams
		if args[1] != nil {
			arg1 = args[1].(db.FailIndexQueueParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueries_FailIndexQueue_Call) Return(err error) *MockQueries_FailIndexQueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueries_FailIndexQueue_Call) RunAndReturn(run func(ctx context.Context, arg db.FailIndexQueueParams) error) *MockQueries_FailIndexQueue_Call {
	_c.Call.Return(run)
	return _c
}

// RequeueStaleIndexQueue provides a mock function for the type MockQueries
func (_mock *MockQueries) RequeueStaleIndexQueue(ctx context.Context, indexType string) (int64, error) {
	ret := _mock.Called(ctx, indexType)

	if len(ret) == 0 {
		panic("no return value specified for RequeueStaleIndexQueue")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, indexType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, indexType)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, indexType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueries_RequeueStaleIndexQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequeueStaleIndexQueue'
type MockQueries_RequeueStaleIndexQueue_Call struct {
	*mock.Call
}

// RequeueStaleIndexQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - indexType string
func (_e *MockQueries_Expecter) RequeueStaleIndexQueue(ctx any, indexType any) *MockQueries_RequeueStaleIndexQueue_Call {
	return &MockQueries_RequeueStaleIndexQueue_Call{Call: _e.mock.On("RequeueStaleIndexQueue", ctx, indexType)}
}

func (_c *MockQueries_RequeueStaleIndexQueue_Call) Run(run func(ctx context.Context, indexType string)) *MockQueries_RequeueStaleIndexQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueries_RequeueStaleIndexQueue_Call) Return(n int64, err error) *MockQueries_RequeueStaleIndexQueue_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQueries_RequeueStaleIndexQueue_Call) RunAndReturn(run func(ctx context.Context, indexType string) (int64, error)) *MockQueries_RequeueStaleIndexQueue_Call {
	_c.Call.Return(run)
	return _c
}

// SeedIndexQueue provides a mock function for the type MockQueries
func (_mock *MockQueries) SeedIndexQueue(ctx context.Context, indexType string) (int64, error) {
	ret := _mock.Called(ctx, indexType)

	if len(ret) == 0 {
		panic("no return value specified for SeedIndexQueue")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, indexType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, indexType)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, indexType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueries_SeedIndexQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SeedIndexQueue'
type MockQueries_SeedIndexQueue_Call struct {
	*mock.Call
}

// SeedIndexQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - indexType string
func (_e *MockQueries_Expecter) SeedIndexQueue(ctx any, indexType any) *MockQueries_SeedIndexQueue_Call {
	return &MockQueries_SeedIndexQueue_Call{Call: _e.mock.On("SeedIndexQueue", ctx, indexType)}
}

func (_c *MockQueries_SeedIndexQueue_Call) Run(run func(ctx context.Context, indexType string)) *MockQueries_SeedIndexQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueries_SeedIndexQueue_Call) Return(n int64, err error) *MockQueries_SeedIndexQueue_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQueries_SeedIndexQueue_Call) RunAndReturn(run func(ctx context.Context, indexType string) (int64, error)) *MockQueries_SeedIndexQueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectStore creates a new instance of MockObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStore {
	mock := &MockObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectStore is an autogenerated mock type for the ObjectStore type
type MockObjectStore struct {
	mock.Mock
}

type MockObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStore) EXPECT() *MockObjectStore_Expecter {
	return &MockObjectStore_Expecter{mock: &_m.Mock}
}

// Stat provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) Stat(ctx context.Context, key string) (storage.ObjectInfo, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 storage.ObjectInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (storage.ObjectInfo, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) storage.ObjectInfo); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(storage.ObjectInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStore_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockObjectStore_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) Stat(ctx any, key any) *MockObjectStore_Stat_Call {
	return &MockObjectStore_Stat_Call{Call: _e.mock.On("Stat", ctx, key)}
}

func (_c *MockObjectStore_Stat_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_Stat_Call) Return(objectInfo storage.ObjectInfo, err error) *MockObjectStore_Stat_Call {
	_c.Call.Return(objectInfo, err)
	return _c
}

func (_c *MockObjectStore_Stat_Call) RunAndReturn(run func(ctx context.Context, key string) (storage.ObjectInfo, error)) *MockObjectStore_Stat_Call {
	_c.Call.Return(run)
	return _c
}
