// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package indexer

import (
	"context"
	"file-indexer/internal/db"
	"file-indexer/internal/storage"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStatQueries creates a new instance of MockStatQueries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatQueries(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatQueries {
	mock := &MockStatQueries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatQueries is an autogenerated mock type for the StatQueries type
type MockStatQueries struct {
	mock.Mock
}

type MockStatQueries_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatQueries) EXPECT() *MockStatQueries_Expecter {
	return &MockStatQueries_Expecter{mock: &_m.Mock}
}

// ClaimIndexStat provides a mock function for the type MockStatQueries
func (_mock *MockStatQueries) ClaimIndexStat(ctx context.Context, arg db.ClaimIndexStatParams) ([]db.ClaimIndexStatRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ClaimIndexStat")
	}

	var r0 []db.ClaimIndexStatRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ClaimIndexStatParams) ([]db.ClaimIndexStatRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ClaimIndexStatParams) []db.ClaimIndexStatRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ClaimIndexStatRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ClaimIndexStatParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatQueries_ClaimIndexStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimIndexStat'
type MockStatQueries_ClaimIndexStat_Call struct {
	*mock.Call
}

// ClaimIndexStat is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ClaimIndexStatParams
func (_e *MockStatQueries_Expecter) ClaimIndexStat(ctx any, arg any) *MockStatQueries_ClaimIndexStat_Call {
	return &MockStatQueries_ClaimIndexStat_Call{Call: _e.mock.On("ClaimIndexStat", ctx, arg)}
}

func (_c *MockStatQueries_ClaimIndexStat_Call) Run(run func(ctx context.Context, arg db.ClaimIndexStatParams)) *MockStatQueries_ClaimIndexStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ClaimIndexStatParams
		if args[1] != nil {
			arg1 = args[1].(db.ClaimIndexStatParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatQueries_ClaimIndexStat_Call) Return(claimIndexStatRows []db.ClaimIndexStatRow, err error) *MockStatQueries_ClaimIndexStat_Call {
	_c.Call.Return(claimIndexStatRows, err)
	return _c
}

func (_c *MockStatQueries_ClaimIndexStat_Call) RunAndReturn(run func(ctx context.Context, arg db.ClaimIndexStatParams) ([]db.ClaimIndexStatRow, error)) *MockStatQueries_ClaimIndexStat_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteIndexStat provides a mock function for the type MockStatQueries
func (_mock *MockStatQueries) CompleteIndexStat(ctx context.Context, arg db.CompleteIndexStatParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CompleteIndexStat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CompleteIndexStatParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStatQueries_CompleteIndexStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteIndexStat'
type MockStatQueries_CompleteIndexStat_Call struct {
	*mock.Call
}

// CompleteIndexStat is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CompleteIndexStatParams
func (_e *MockStatQueries_Expecter) CompleteIndexStat(ctx any, arg any) *MockStatQueries_CompleteIndexStat_Call {
	return &MockStatQueries_CompleteIndexStat_Call{Call: _e.mock.On("CompleteIndexStat", ctx, arg)}
}

func (_c *MockStatQueries_CompleteIndexStat_Call) Run(run func(ctx context.Context, arg db.CompleteIndexStatParams)) *MockStatQueries_CompleteIndexStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CompleteIndexStatParams
		if args[1] != nil {
			arg1 = args[1].(db.CompleteIndexStatParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatQueries_CompleteIndexStat_Call) Return(err error) *MockStatQueries_CompleteIndexStat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStatQueries_CompleteIndexStat_Call) RunAndReturn(run func(ctx context.Context, arg db.CompleteIndexStatParams) error) *MockStatQueries_CompleteIndexStat_Call {
	_c.Call.Return(run)
	return _c
}

// FailIndexStat provides a mock function for the type MockStatQueries
func (_mock *MockStatQueries) FailIndexStat(ctx context.Context, arg db.FailIndexStatParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FailIndexStat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.FailIndexStatParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStatQueries_FailIndexStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailIndexStat'
type MockStatQueries_FailIndexStat_Call struct {
	*mock.Call
}

// FailIndexStat is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.FailIndexStatParams
func (_e *MockStatQueries_Expecter) FailIndexStat(ctx any, arg any) *MockStatQueries_FailIndexStat_Call {
	return &MockStatQueries_FailIndexStat_Call{Call: _e.mock.On("FailIndexStat", ctx, arg)}
}

func (_c *MockStatQueries_FailIndexStat_Call) Run(run func(ctx context.Context, arg db.FailIndexStatParams)) *MockStatQueries_FailIndexStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.FailIndexStatParams
		if args[1] != nil {
			arg1 = args[1].(db.FailIndexStatParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatQueries_FailIndexStat_Call) Return(err error) *MockStatQueries_FailIndexStat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStatQueries_FailIndexStat_Call) RunAndReturn(run func(ctx context.Context, arg db.FailIndexStatParams) error) *MockStatQueries_FailIndexStat_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseIndexStat provides a mock function for the type MockStatQueries
func (_mock *MockStatQueries) ReleaseIndexStat(ctx context.Context, fileID int64) error {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseIndexStat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStatQueries_ReleaseIndexStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseIndexStat'
type MockStatQueries_ReleaseIndexStat_Call struct {
	*mock.Call
}

// ReleaseIndexStat is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID int64
func (_e *MockStatQueries_Expecter) ReleaseIndexStat(ctx any, fileID any) *MockStatQueries_ReleaseIndexStat_Call {
	return &MockStatQueries_ReleaseIndexStat_Call{Call: _e.mock.On("ReleaseIndexStat", ctx, fileID)}
}

func (_c *MockStatQueries_ReleaseIndexStat_Call) Run(run func(ctx context.Context, fileID int64)) *MockStatQueries_ReleaseIndexStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatQueries_ReleaseIndexStat_Call) Return(err error) *MockStatQueries_ReleaseIndexStat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStatQueries_ReleaseIndexStat_Call) RunAndReturn(run func(ctx context.Context, fileID int64) error) *MockStatQueries_ReleaseIndexStat_Call {
	_c.Call.Return(run)
	return _c
}

// SeedIndexStat provides a mock function for the type MockStatQueries
func (_mock *MockStatQueries) SeedIndexStat(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SeedIndexStat")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatQueries_SeedIndexStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SeedIndexStat'
type MockStatQueries_SeedIndexStat_Call struct {
	*mock.Call
}

// SeedIndexStat is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatQueries_Expecter) SeedIndexStat(ctx any) *MockStatQueries_SeedIndexStat_Call {
	return &MockStatQueries_SeedIndexStat_Call{Call: _e.mock.On("SeedIndexStat", ctx)}
}

func (_c *MockStatQueries_SeedIndexStat_Call) Run(run func(ctx context.Context)) *MockStatQueries_SeedIndexStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatQueries_SeedIndexStat_Call) Return(n int64, err error) *MockStatQueries_SeedIndexStat_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStatQueries_SeedIndexStat_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockStatQueries_SeedIndexStat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectStore creates a new instance of MockObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStore {
	mock := &MockObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectStore is an autogenerated mock type for the ObjectStore type
type MockObjectStore struct {
	mock.Mock
}

type MockObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStore) EXPECT() *MockObjectStore_Expecter {
	return &MockObjectStore_Expecter{mock: &_m.Mock}
}

// Stat provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) Stat(ctx context.Context, key string) (storage.ObjectInfo, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 storage.ObjectInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (storage.ObjectInfo, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) storage.ObjectInfo); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(storage.ObjectInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStore_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockObjectStore_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) Stat(ctx any, key any) *MockObjectStore_Stat_Call {
	return &MockObjectStore_Stat_Call{Call: _e.mock.On("Stat", ctx, key)}
}

func (_c *MockObjectStore_Stat_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_Stat_Call) Return(objectInfo storage.ObjectInfo, err error) *MockObjectStore_Stat_Call {
	_c.Call.Return(objectInfo, err)
	return _c
}

func (_c *MockObjectStore_Stat_Call) RunAndReturn(run func(ctx context.Context, key string) (storage.ObjectInfo, error)) *MockObjectStore_Stat_Call {
	_c.Call.Return(run)
	return _c
}
