// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: indexer.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Indexer_Index_FullMethodName = "/service.Indexer/Index"
)

// IndexerClient is the client API for Indexer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndexerClient interface {
	Index(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IndexRequest, IndexResponse], error)
}

type indexerClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexerClient(cc grpc.ClientConnInterface) IndexerClient {
	return &indexerClient{cc}
}

func (c *indexerClient) Index(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IndexRequest, IndexResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Indexer_ServiceDesc.Streams[0], Indexer_Index_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IndexRequest, IndexResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Indexer_IndexClient = grpc.ClientStreamingClient[IndexRequest, IndexResponse]

// IndexerServer is the server API for Indexer service.
// All implementations must embed UnimplementedIndexerServer
// for forward compatibility.
type IndexerServer interface {
	Index(grpc.ClientStreamingServer[IndexRequest, IndexResponse]) error
	mustEmbedUnimplementedIndexerServer()
}

// UnimplementedIndexerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexerServer struct{}

func (UnimplementedIndexerServer) Index(grpc.ClientStreamingServer[IndexRequest, IndexResponse]) error {
	return status.Error(codes.Unimplemented, "method Index not implemented")
}
func (UnimplementedIndexerServer) mustEmbedUnimplementedIndexerServer() {}
func (UnimplementedIndexerServer) testEmbeddedByValue()                 {}

// UnsafeIndexerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexerServer will
// result in compilation errors.
type UnsafeIndexerServer interface {
	mustEmbedUnimplementedIndexerServer()
}

func RegisterIndexerServer(s grpc.ServiceRegistrar, srv IndexerServer) {
	// If the following call panics, it indicates UnimplementedIndexerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Indexer_ServiceDesc, srv)
}

func _Indexer_Index_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IndexerServer).Index(&grpc.GenericServerStream[IndexRequest, IndexResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Indexer_IndexServer = grpc.ClientStreamingServer[IndexRequest, IndexResponse]

// Indexer_ServiceDesc is the grpc.ServiceDesc for Indexer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Indexer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Indexer",
	HandlerType: (*IndexerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Index",
			Handler:       _Indexer_Index_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "indexer.proto",
}
