apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      containers:
        - name: indexer
          image: indexer
          ports:
            - name: grpc
              containerPort: 50051
          env:
            - name: GRPC_ADDR
              value: ":50051"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "mysecretpassword"
            - name: DB_NAME
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: indexer
spec:
  selector:
    app: indexer
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
