apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-stat
spec:
  template:
    spec:
      containers:
        - name: index-stat
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
