apiVersion: batch/v1
kind: Job
metadata:
  name: crawler
spec:
  template:
    spec:
      containers:
        - name: crawler
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
