apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: file-indexer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaketerrito/file-indexer.git
    targetRevision: v0.1.0
    path: deploy/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: file-indexer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
