// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: advisory_lock.sql

package db

import (
	"context"
)

const advisoryLock = `-- name: AdvisoryLock :exec
SELECT pg_advisory_lock($1::int, hashtext($2)::int)
`

type AdvisoryLockParams struct {
	Namespace int32
	Key       string
}

// Acquire a session-scoped advisory lock on a namespaced 32-bit hash of
// key. The files-service move path uses these locks (two per move, taken
// in deterministic byte order) so moves are safe across multiple replicas.
// A session lock is used rather than a transaction-scoped lock because the
// critical section spans S3 I/O outside any database transaction. The lock
// is automatically released when the session disconnects.
func (q *Queries) AdvisoryLock(ctx context.Context, arg AdvisoryLockParams) error {
	_, err := q.db.Exec(ctx, advisoryLock, arg.Namespace, arg.Key)
	return err
}

const advisoryUnlock = `-- name: AdvisoryUnlock :exec
SELECT pg_advisory_unlock($1::int, hashtext($2)::int)
`

type AdvisoryUnlockParams struct {
	Namespace int32
	Key       string
}

// Release a session-scoped advisory lock acquired by AdvisoryLock. This is
// best-effort cleanup before returning the pinned connection to the pool;
// the real safety guarantee comes from the lock being bound to the session.
func (q *Queries) AdvisoryUnlock(ctx context.Context, arg AdvisoryUnlockParams) error {
	_, err := q.db.Exec(ctx, advisoryUnlock, arg.Namespace, arg.Key)
	return err
}
