// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (key, content_type, size_bytes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, key, content_type, size_bytes, created_at, updated_at
`

type CreateFileParams struct {
	Key         string
	ContentType pgtype.Text
	SizeBytes   pgtype.Int8
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.Key,
		arg.ContentType,
		arg.SizeBytes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :one
DELETE FROM files
WHERE id = $1
RETURNING id, key, content_type, size_bytes, created_at, updated_at
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRow(ctx, deleteFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, key, content_type, size_bytes, created_at, updated_at FROM files
WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFilesByIDs = `-- name: GetFilesByIDs :many
SELECT id, key, content_type, size_bytes, created_at, updated_at FROM files
WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetFilesByIDs(ctx context.Context, dollar_1 []int64) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByCreatedAtAsc = `-- name: ListFilesByCreatedAtAsc :many
SELECT id, key, content_type, size_bytes, created_at, updated_at FROM files
WHERE key LIKE $1
  AND ($2::text = '' OR content_type LIKE $2)
  AND (NOT $3::bool OR (created_at, id) > ($4::timestamptz, $5::bigint))
ORDER BY created_at ASC, id ASC
LIMIT $6
`

type ListFilesByCreatedAtAscParams struct {
	KeyPattern         string
	ContentTypePattern string
	HasCursor          bool
	LastCreatedAt      pgtype.Timestamptz
	LastID             int64
	PageLimit          int32
}

func (q *Queries) ListFilesByCreatedAtAsc(ctx context.Context, arg ListFilesByCreatedAtAscParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByCreatedAtAsc,
		arg.KeyPattern,
		arg.ContentTypePattern,
		arg.HasCursor,
		arg.LastCreatedAt,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByCreatedAtDesc = `-- name: ListFilesByCreatedAtDesc :many
SELECT id, key, content_type, size_bytes, created_at, updated_at FROM files
WHERE key LIKE $1
  AND ($2::text = '' OR content_type LIKE $2)
  AND (NOT $3::bool OR (created_at, id) < ($4::timestamptz, $5::bigint))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListFilesByCreatedAtDescParams struct {
	KeyPattern         string
	ContentTypePattern string
	HasCursor          bool
	LastCreatedAt      pgtype.Timestamptz
	LastID             int64
	PageLimit          int32
}

func (q *Queries) ListFilesByCreatedAtDesc(ctx context.Context, arg ListFilesByCreatedAtDescParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByCreatedAtDesc,
		arg.KeyPattern,
		arg.ContentTypePattern,
		arg.HasCursor,
		arg.LastCreatedAt,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByKeyAsc = `-- name: ListFilesByKeyAsc :many

SELECT id, key, content_type, size_bytes, created_at, updated_at FROM files
WHERE key LIKE $1
  AND ($2::text = '' OR content_type LIKE $2)
  AND (NOT $3::bool OR (key, id) > ($4::text, $5::bigint))
ORDER BY key ASC, id ASC
LIMIT $6
`

type ListFilesByKeyAscParams struct {
	KeyPattern         string
	ContentTypePattern string
	HasCursor          bool
	LastKey            string
	LastID             int64
	PageLimit          int32
}

// The ListFilesBy* queries below implement keyset pagination for the search
// service: one query per (sort field, direction), always tie-breaking on id
// so cursors are stable. key_pattern and content_type_pattern are LIKE
// patterns built (and escaped) by the caller; an empty content_type_pattern
// disables the content type filter. When has_cursor is false the last_*
// arguments are ignored.
func (q *Queries) ListFilesByKeyAsc(ctx context.Context, arg ListFilesByKeyAscParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByKeyAsc,
		arg.KeyPattern,
		arg.ContentTypePattern,
		arg.HasCursor,
		arg.LastKey,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByKeyDesc = `-- name: ListFilesByKeyDesc :many
SELECT id, key, content_type, size_bytes, created_at, updated_at FROM files
WHERE key LIKE $1
  AND ($2::text = '' OR content_type LIKE $2)
  AND (NOT $3::bool OR (key, id) < ($4::text, $5::bigint))
ORDER BY key DESC, id DESC
LIMIT $6
`

type ListFilesByKeyDescParams struct {
	KeyPattern         string
	ContentTypePattern string
	HasCursor          bool
	LastKey            string
	LastID             int64
	PageLimit          int32
}

func (q *Queries) ListFilesByKeyDesc(ctx context.Context, arg ListFilesByKeyDescParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByKeyDesc,
		arg.KeyPattern,
		arg.ContentTypePattern,
		arg.HasCursor,
		arg.LastKey,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesBySizeAsc = `-- name: ListFilesBySizeAsc :many
SELECT id, key, content_type, size_bytes, created_at, updated_at FROM files
WHERE key LIKE $1
  AND ($2::text = '' OR content_type LIKE $2)
  AND (NOT $3::bool OR (COALESCE(size_bytes, 0), id) > ($4::bigint, $5::bigint))
ORDER BY COALESCE(size_bytes, 0) ASC, id ASC
LIMIT $6
`

type ListFilesBySizeAscParams struct {
	KeyPattern         string
	ContentTypePattern string
	HasCursor          bool
	LastSize           int64
	LastID             int64
	PageLimit          int32
}

func (q *Queries) ListFilesBySizeAsc(ctx context.Context, arg ListFilesBySizeAscParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesBySizeAsc,
		arg.KeyPattern,
		arg.ContentTypePattern,
		arg.HasCursor,
		arg.LastSize,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesBySizeDesc = `-- name: ListFilesBySizeDesc :many
SELECT id, key, content_type, size_bytes, created_at, updated_at FROM files
WHERE key LIKE $1
  AND ($2::text = '' OR content_type LIKE $2)
  AND (NOT $3::bool OR (COALESCE(size_bytes, 0), id) < ($4::bigint, $5::bigint))
ORDER BY COALESCE(size_bytes, 0) DESC, id DESC
LIMIT $6
`

type ListFilesBySizeDescParams struct {
	KeyPattern         string
	ContentTypePattern string
	HasCursor          bool
	LastSize           int64
	LastID             int64
	PageLimit          int32
}

func (q *Queries) ListFilesBySizeDesc(ctx context.Context, arg ListFilesBySizeDescParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesBySizeDesc,
		arg.KeyPattern,
		arg.ContentTypePattern,
		arg.HasCursor,
		arg.LastSize,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileMetadata = `-- name: UpdateFileMetadata :exec
UPDATE files
SET content_type = $2,
    size_bytes = $3,
    updated_at = date_trunc('second', $4::timestamptz)
WHERE id = $1
`

type UpdateFileMetadataParams struct {
	ID          int64
	ContentType pgtype.Text
	SizeBytes   pgtype.Int8
	UpdatedAt   pgtype.Timestamptz
}

// Stat indexer result write: metadata the S3 listing cannot provide (content
// type) plus authoritative size/mtime from StatObject. updated_at is
// truncated to whole seconds to match UpsertFiles (see the comment there);
// otherwise the crawler's change detection would flag every indexed file.
func (q *Queries) UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) error {
	_, err := q.db.Exec(ctx, updateFileMetadata,
		arg.ID,
		arg.ContentType,
		arg.SizeBytes,
		arg.UpdatedAt,
	)
	return err
}

const upsertFiles = `-- name: UpsertFiles :many
INSERT INTO files (key, size_bytes, created_at, updated_at)
SELECT t.key, t.size_bytes, date_trunc('second', t.last_modified), date_trunc('second', t.last_modified)
FROM (
    SELECT unnest($1::text[])                  AS key,
           unnest($2::bigint[])               AS size_bytes,
           unnest($3::timestamptz[]) AS last_modified
) AS t
ON CONFLICT (key) DO UPDATE
SET size_bytes = EXCLUDED.size_bytes,
    updated_at = EXCLUDED.updated_at
WHERE files.size_bytes IS DISTINCT FROM EXCLUDED.size_bytes
   OR files.updated_at IS DISTINCT FROM EXCLUDED.updated_at
RETURNING id
`

type UpsertFilesParams struct {
	Keys          []string
	Sizes         []int64
	LastModifieds []pgtype.Timestamptz
}

// Crawler ingest: register discovered objects idempotently. created_at and
// updated_at both start as the object's S3 last-modified time. On re-crawl,
// the row is only touched when size or last-modified actually changed, so
// RETURNING yields exactly the new + changed file ids; the crawler feeds
// those into ResetIndexStat to trigger re-indexing (new files have no
// index_stat row yet and are picked up by SeedIndexStat instead).
//
// Timestamps are truncated to whole seconds: the stat indexer also writes
// updated_at, and its source (the HTTP Last-Modified header) only has second
// precision while listings carry sub-second precision. Truncating on every
// write keeps the change comparison below from false-flagging files whose
// updated_at was last written by the indexer.
func (q *Queries) UpsertFiles(ctx context.Context, arg UpsertFilesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, upsertFiles, arg.Keys, arg.Sizes, arg.LastModifieds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
