// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: index_queue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIndexQueue = `-- name: ClaimIndexQueue :many
WITH candidates AS (
    SELECT file_id
    FROM index_queue
    WHERE index_type = $1::text
      AND ((status = 'pending' AND next_attempt_at <= now())
           OR (status = 'claimed' AND now() - claimed_at >= $2::interval))
    ORDER BY next_attempt_at
    LIMIT $3
    FOR UPDATE SKIP LOCKED
),
claimed AS (
    UPDATE index_queue q
    SET status = 'claimed', attempts = q.attempts + 1, claimed_at = now(), updated_at = now()
    FROM candidates c
    WHERE q.index_type = $1::text AND q.file_id = c.file_id
    RETURNING q.file_id, q.attempts
)
SELECT c.file_id, c.attempts, f.key
FROM claimed c
JOIN files f ON f.id = c.file_id
`

type ClaimIndexQueueParams struct {
	IndexType    string
	StaleTimeout pgtype.Interval
	BatchSize    int32
}

type ClaimIndexQueueRow struct {
	FileID   int64
	Attempts int32
	Key      string
}

// Atomically claim a batch of jobs for one index type. FOR UPDATE SKIP
// LOCKED lets concurrent claimers (any number of pods) grab disjoint
// batches without blocking. Rows claimed longer than stale_timeout
// (a crashed instance's claim TTL) are reclaimed alongside pending rows.
func (q *Queries) ClaimIndexQueue(ctx context.Context, arg ClaimIndexQueueParams) ([]ClaimIndexQueueRow, error) {
	rows, err := q.db.Query(ctx, claimIndexQueue, arg.IndexType, arg.StaleTimeout, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimIndexQueueRow
	for rows.Next() {
		var i ClaimIndexQueueRow
		if err := rows.Scan(&i.FileID, &i.Attempts, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeIndexQueue = `-- name: CompleteIndexQueue :exec
UPDATE index_queue q
SET status = 'done',
    last_error = NULL,
    updated_at = now(),
    mark = f.marked_at
FROM files f
WHERE q.index_type = $1::text
  AND q.file_id = $2
  AND f.id = $2
`

type CompleteIndexQueueParams struct {
	IndexType string
	FileID    int64
}

// Record a successful run: status flip and mark capture. mark copies
// files.marked_at at completion time so that an edit arriving mid-run
// (bumping marked_at) still triggers a re-index on the next seed. Callers
// run this in the same transaction as their result-table write so a job is
// never marked done without its result persisted, or vice versa.
func (q *Queries) CompleteIndexQueue(ctx context.Context, arg CompleteIndexQueueParams) error {
	_, err := q.db.Exec(ctx, completeIndexQueue, arg.IndexType, arg.FileID)
	return err
}

const failIndexQueue = `-- name: FailIndexQueue :exec
UPDATE index_queue
SET status = CASE WHEN $1::bool THEN 'error' ELSE 'pending' END,
    next_attempt_at = $2::timestamptz,
    last_error = $3,
    updated_at = now()
WHERE index_type = $4::text
  AND file_id = $5
`

type FailIndexQueueParams struct {
	Exhausted     bool
	NextAttemptAt pgtype.Timestamptz
	LastError     pgtype.Text
	IndexType     string
	FileID        int64
}

// Record a failed attempt. When the runner has exhausted retries it sets
// exhausted, parking the row as error until manually reset; otherwise the
// row returns to pending and becomes claimable at next_attempt_at.
func (q *Queries) FailIndexQueue(ctx context.Context, arg FailIndexQueueParams) error {
	_, err := q.db.Exec(ctx, failIndexQueue,
		arg.Exhausted,
		arg.NextAttemptAt,
		arg.LastError,
		arg.IndexType,
		arg.FileID,
	)
	return err
}

const requeueStaleIndexQueue = `-- name: RequeueStaleIndexQueue :execrows
UPDATE index_queue q
SET status = 'pending',
    attempts = 0,
    next_attempt_at = now(),
    last_error = NULL,
    mark = NULL,
    updated_at = now()
FROM files f
WHERE q.file_id = f.id
  AND q.index_type = $1::text
  AND q.status IN ('done', 'pending')
  AND q.mark IS NOT NULL
  AND q.mark < f.marked_at
`

// Re-enqueue done and pending rows whose stored mark is older than
// files.marked_at. Done rows were completed against a prior snapshot;
// pending rows may carry a stale mark from an earlier re-enqueue. In both
// cases resetting the row ensures the next claim re-indexes the current
// content. Claimed rows are in-flight and left alone; error rows stay
// parked until manually reset.
func (q *Queries) RequeueStaleIndexQueue(ctx context.Context, indexType string) (int64, error) {
	result, err := q.db.Exec(ctx, requeueStaleIndexQueue, indexType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedIndexQueue = `-- name: SeedIndexQueue :execrows

INSERT INTO index_queue (index_type, file_id)
SELECT $1::text, f.id
FROM files f
WHERE NOT EXISTS (
    SELECT 1 FROM index_queue q
    WHERE q.index_type = $1::text AND q.file_id = f.id
)
ON CONFLICT (index_type, file_id) DO NOTHING
`

// Queue queries shared by every index type. All statements are scoped by
// index_type so unrelated pipelines never interfere. The lifecycle is:
//
//	(no row)  --seed-->  pending  --claim-->  claimed  --complete-->  done
//	                       ^                    |
//	                       +------fail----------+--(attempts exhausted)--> error
//
// Staleness detection: the seed step also re-enqueues done rows whose
// stored mark no longer matches files.marked_at, so an edited object is
// automatically re-indexed on the next seed without the crawler needing to
// know which index types exist.
//
// Timing policy (backoff, claim TTL, max attempts) lives in the runner
// package; these queries only persist the decisions it makes.
// Discover files that have no index_queue row yet for this index type and
// enqueue them as pending. Self-seeding means the crawler does not need to
// know which index types exist; a new index type discovers its entire
// backlog on startup.
func (q *Queries) SeedIndexQueue(ctx context.Context, indexType string) (int64, error) {
	result, err := q.db.Exec(ctx, seedIndexQueue, indexType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
