// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: index_stat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIndexStat = `-- name: ClaimIndexStat :many
WITH candidates AS (
    SELECT file_id
    FROM index_stat
    WHERE (status = 'pending' AND next_attempt_at <= now())
       OR (status = 'claimed' AND claimed_at <= $1::timestamptz)
    ORDER BY next_attempt_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
),
claimed AS (
    UPDATE index_stat s
    SET status = 'claimed', attempts = s.attempts + 1, claimed_at = now(), updated_at = now()
    FROM candidates c
    WHERE s.file_id = c.file_id
    RETURNING s.file_id, s.attempts
)
SELECT c.file_id, c.attempts, f.key
FROM claimed c
JOIN files f ON f.id = c.file_id
`

type ClaimIndexStatParams struct {
	StaleBefore pgtype.Timestamptz
	BatchSize   int32
}

type ClaimIndexStatRow struct {
	FileID   int64
	Attempts int32
	Key      string
}

// Atomically claim a batch of jobs for one worker pool poll. FOR UPDATE SKIP
// LOCKED lets concurrent claimers grab disjoint batches without blocking.
// Rows stuck in claimed since before stale_before (a crashed worker's claim
// TTL cutoff) are reclaimed alongside pending rows.
func (q *Queries) ClaimIndexStat(ctx context.Context, arg ClaimIndexStatParams) ([]ClaimIndexStatRow, error) {
	rows, err := q.db.Query(ctx, claimIndexStat, arg.StaleBefore, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimIndexStatRow
	for rows.Next() {
		var i ClaimIndexStatRow
		if err := rows.Scan(&i.FileID, &i.Attempts, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeIndexStat = `-- name: CompleteIndexStat :exec
UPDATE index_stat
SET status = 'done', last_error = NULL, updated_at = now()
WHERE file_id = $1
`

func (q *Queries) CompleteIndexStat(ctx context.Context, fileID int64) error {
	_, err := q.db.Exec(ctx, completeIndexStat, fileID)
	return err
}

const failIndexStat = `-- name: FailIndexStat :exec
UPDATE index_stat
SET status = CASE WHEN $1::bool THEN 'error' ELSE 'pending' END,
    next_attempt_at = $2::timestamptz,
    last_error = $3,
    updated_at = now()
WHERE file_id = $4
`

type FailIndexStatParams struct {
	Exhausted     bool
	NextAttemptAt pgtype.Timestamptz
	LastError     pgtype.Text
	FileID        int64
}

// Record a failed attempt. When the worker framework has exhausted retries it
// sets exhausted, parking the row as error until manually reset; otherwise
// the row returns to pending and becomes claimable at next_attempt_at.
func (q *Queries) FailIndexStat(ctx context.Context, arg FailIndexStatParams) error {
	_, err := q.db.Exec(ctx, failIndexStat,
		arg.Exhausted,
		arg.NextAttemptAt,
		arg.LastError,
		arg.FileID,
	)
	return err
}

const resetIndexStat = `-- name: ResetIndexStat :execrows
UPDATE index_stat
SET status = 'pending', attempts = 0, next_attempt_at = now(), last_error = NULL, updated_at = now()
WHERE file_id = ANY ($1::bigint[])
  AND status <> 'pending'
`

// Re-enqueue specific files (e.g. the crawler detected the object changed in
// S3). Done/error/claimed rows all return to pending; attempts restart since
// this is logically a new piece of work.
func (q *Queries) ResetIndexStat(ctx context.Context, fileIds []int64) (int64, error) {
	result, err := q.db.Exec(ctx, resetIndexStat, fileIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedIndexStat = `-- name: SeedIndexStat :execrows

INSERT INTO index_stat (file_id)
SELECT f.id
FROM files f
WHERE NOT EXISTS (SELECT 1 FROM index_stat s WHERE s.file_id = f.id)
ON CONFLICT (file_id) DO NOTHING
`

// Queue queries for the stat indexer worker pool. The lifecycle is:
//
//	(no row)  --seed-->  pending  --claim-->  claimed  --complete-->  done
//	                       ^                    |
//	                       +------fail----------+--(attempts exhausted)--> error
//
// Timing policy (backoff, claim TTL, max attempts) lives in the worker
// framework; these queries only persist the decisions it makes.
// Discover files that have no index_stat row yet and enqueue them as
// pending. Self-seeding means the crawler does not need to know which index
// types exist; a new worker type discovers its entire backlog on startup.
func (q *Queries) SeedIndexStat(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, seedIndexStat)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
