// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID        int64
	Key       string
	CreatedAt pgtype.Timestamptz
	MarkedAt  pgtype.Timestamptz
}

type FileInfo struct {
	ID            int64
	Key           string
	CreatedAt     pgtype.Timestamptz
	ContentType   pgtype.Text
	SizeBytes     pgtype.Int8
	LastModified  pgtype.Timestamptz
	PreviewKey    pgtype.Text
	PreviewWidth  pgtype.Int4
	PreviewHeight pgtype.Int4
}

type IndexPreviewResult struct {
	FileID     int64
	PreviewKey string
	Width      int32
	Height     int32
	UpdatedAt  pgtype.Timestamptz
}

type IndexQueue struct {
	IndexType     string
	FileID        int64
	Status        string
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	ClaimedAt     pgtype.Timestamptz
	LastError     pgtype.Text
	UpdatedAt     pgtype.Timestamptz
	Mark          pgtype.Timestamptz
}

type IndexStatResult struct {
	FileID       int64
	ContentType  string
	SizeBytes    int64
	LastModified pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
