// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID        int64
	Key       string
	CreatedAt pgtype.Timestamptz
	MarkedAt  pgtype.Timestamptz
}

type FileInfo struct {
	ID           int64
	Key          string
	CreatedAt    pgtype.Timestamptz
	ContentType  pgtype.Text
	SizeBytes    pgtype.Int8
	LastModified pgtype.Timestamptz
}

type IndexStat struct {
	FileID        int64
	Status        string
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	ClaimedAt     pgtype.Timestamptz
	LastError     pgtype.Text
	UpdatedAt     pgtype.Timestamptz
	Mark          pgtype.Timestamptz
	ContentType   pgtype.Text
	SizeBytes     pgtype.Int8
	LastModified  pgtype.Timestamptz
}
