name: lint-proto
on:
  push:
    branches: [main]
    paths:
      - "proto/**"
      - ".github/workflows/lint-proto.yml"
  pull_request:
    branches: [main]
    paths:
      - "proto/**"
      - ".github/workflows/lint-proto.yml"

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-proto:
    name: lint-proto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1
        with:
          input: proto
          # renovate: datasource=github-releases depName=bufbuild/buf
          version: 1.71.0
          lint: true
          format: true
          push: false
