// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package crawler

import (
	"context"
	"file-indexer/internal/db"
	"file-indexer/internal/storage"

	mock "github.com/stretchr/testify/mock"
)

// NewMockObjectStore creates a new instance of MockObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStore {
	mock := &MockObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectStore is an autogenerated mock type for the ObjectStore type
type MockObjectStore struct {
	mock.Mock
}

type MockObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStore) EXPECT() *MockObjectStore_Expecter {
	return &MockObjectStore_Expecter{mock: &_m.Mock}
}

// Walk provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) Walk(ctx context.Context, fn func(storage.ObjectInfo) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Walk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(storage.ObjectInfo) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectStore_Walk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Walk'
type MockObjectStore_Walk_Call struct {
	*mock.Call
}

// Walk is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(storage.ObjectInfo) error
func (_e *MockObjectStore_Expecter) Walk(ctx any, fn any) *MockObjectStore_Walk_Call {
	return &MockObjectStore_Walk_Call{Call: _e.mock.On("Walk", ctx, fn)}
}

func (_c *MockObjectStore_Walk_Call) Run(run func(ctx context.Context, fn func(storage.ObjectInfo) error)) *MockObjectStore_Walk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(storage.ObjectInfo) error
		if args[1] != nil {
			arg1 = args[1].(func(storage.ObjectInfo) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_Walk_Call) Return(err error) *MockObjectStore_Walk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectStore_Walk_Call) RunAndReturn(run func(ctx context.Context, fn func(storage.ObjectInfo) error) error) *MockObjectStore_Walk_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileStore creates a new instance of MockFileStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileStore {
	mock := &MockFileStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileStore is an autogenerated mock type for the FileStore type
type MockFileStore struct {
	mock.Mock
}

type MockFileStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileStore) EXPECT() *MockFileStore_Expecter {
	return &MockFileStore_Expecter{mock: &_m.Mock}
}

// InsertFiles provides a mock function for the type MockFileStore
func (_mock *MockFileStore) InsertFiles(ctx context.Context, keys []string) ([]int64, error) {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for InsertFiles")
	}

	var r0 []int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]int64, error)); ok {
		return returnFunc(ctx, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []int64); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStore_InsertFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertFiles'
type MockFileStore_InsertFiles_Call struct {
	*mock.Call
}

// InsertFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockFileStore_Expecter) InsertFiles(ctx any, keys any) *MockFileStore_InsertFiles_Call {
	return &MockFileStore_InsertFiles_Call{Call: _e.mock.On("InsertFiles", ctx, keys)}
}

func (_c *MockFileStore_InsertFiles_Call) Run(run func(ctx context.Context, keys []string)) *MockFileStore_InsertFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileStore_InsertFiles_Call) Return(int64s []int64, err error) *MockFileStore_InsertFiles_Call {
	_c.Call.Return(int64s, err)
	return _c
}

func (_c *MockFileStore_InsertFiles_Call) RunAndReturn(run func(ctx context.Context, keys []string) ([]int64, error)) *MockFileStore_InsertFiles_Call {
	_c.Call.Return(run)
	return _c
}

// ResetChangedIndexStat provides a mock function for the type MockFileStore
func (_mock *MockFileStore) ResetChangedIndexStat(ctx context.Context, arg db.ResetChangedIndexStatParams) (int64, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ResetChangedIndexStat")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ResetChangedIndexStatParams) (int64, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ResetChangedIndexStatParams) int64); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ResetChangedIndexStatParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStore_ResetChangedIndexStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetChangedIndexStat'
type MockFileStore_ResetChangedIndexStat_Call struct {
	*mock.Call
}

// ResetChangedIndexStat is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ResetChangedIndexStatParams
func (_e *MockFileStore_Expecter) ResetChangedIndexStat(ctx any, arg any) *MockFileStore_ResetChangedIndexStat_Call {
	return &MockFileStore_ResetChangedIndexStat_Call{Call: _e.mock.On("ResetChangedIndexStat", ctx, arg)}
}

func (_c *MockFileStore_ResetChangedIndexStat_Call) Run(run func(ctx context.Context, arg db.ResetChangedIndexStatParams)) *MockFileStore_ResetChangedIndexStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ResetChangedIndexStatParams
		if args[1] != nil {
			arg1 = args[1].(db.ResetChangedIndexStatParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileStore_ResetChangedIndexStat_Call) Return(n int64, err error) *MockFileStore_ResetChangedIndexStat_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFileStore_ResetChangedIndexStat_Call) RunAndReturn(run func(ctx context.Context, arg db.ResetChangedIndexStatParams) (int64, error)) *MockFileStore_ResetChangedIndexStat_Call {
	_c.Call.Return(run)
	return _c
}
