// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package crawler

import (
	"context"
	"file-indexer/internal/pb/service/v1"

	mock "github.com/stretchr/testify/mock"
)

// NewMockObjectStore creates a new instance of MockObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStore {
	mock := &MockObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectStore is an autogenerated mock type for the ObjectStore type
type MockObjectStore struct {
	mock.Mock
}

type MockObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStore) EXPECT() *MockObjectStore_Expecter {
	return &MockObjectStore_Expecter{mock: &_m.Mock}
}

// Walk provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) Walk(ctx context.Context, fn func(*pb.FileRef) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Walk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(*pb.FileRef) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectStore_Walk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Walk'
type MockObjectStore_Walk_Call struct {
	*mock.Call
}

// Walk is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(*pb.FileRef) error
func (_e *MockObjectStore_Expecter) Walk(ctx any, fn any) *MockObjectStore_Walk_Call {
	return &MockObjectStore_Walk_Call{Call: _e.mock.On("Walk", ctx, fn)}
}

func (_c *MockObjectStore_Walk_Call) Run(run func(ctx context.Context, fn func(*pb.FileRef) error)) *MockObjectStore_Walk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(*pb.FileRef) error
		if args[1] != nil {
			arg1 = args[1].(func(*pb.FileRef) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_Walk_Call) Return(err error) *MockObjectStore_Walk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectStore_Walk_Call) RunAndReturn(run func(ctx context.Context, fn func(*pb.FileRef) error) error) *MockObjectStore_Walk_Call {
	_c.Call.Return(run)
	return _c
}
